/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface ActivatorTrigger : NSObject {

	NSString* _eventName;
	int _forWhat;
	NSString* _scriptTitle;

}

@property (nonatomic,retain) NSString * eventName;                //@synthesize eventName=_eventName - In the implementation block
@property (assign,nonatomic) int forWhat;                         //@synthesize forWhat=_forWhat - In the implementation block
@property (nonatomic,retain) NSString * scriptTitle;              //@synthesize scriptTitle=_scriptTitle - In the implementation block
-(NSString *)scriptTitle;
-(id)initWithEventName:(id)arg1 andForWhat:(int)arg2 andScriptTitle:(id)arg3 ;
-(void)setScriptTitle:(NSString *)arg1 ;
-(void)setForWhat:(int)arg1 ;
-(int)forWhat;
-(void)setEventName:(NSString *)arg1 ;
-(NSString *)eventName;
@end

