/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface ActivatorManager : NSObject
+(id)getActivatorTriggerByScriptTitle:(id)arg1 ;
+(id)getActivatorTriggerAll;
+(id)getActivatorTriggerForControlPanel;
+(id)getActivatorTriggerForStartStopPlaying;
+(id)compatibleModesOfEventAssigned:(id)arg1 ;
+(id)compatibleModesOfEvent:(id)arg1 ;
+(char)allowedToUnassignEvent:(id)arg1 fromListener:(id)arg2 ;
+(char)isEventAssigned:(id)arg1 forWhat:(int)arg2 andScriptTitle:(id)arg3 ;
+(void)unassignActivatorTrigger:(id)arg1 forModes:(id)arg2 ;
+(void)assignActivatorTrigger:(id)arg1 forModes:(id)arg2 ;
+(void)keepConsistentBetweenActivatorAndDb;
+(void)initControlActions;
+(id)getActivatorTriggerByEventName:(id)arg1 ;
@end

