/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewController.h>

@class UITableView, NSArray;

@interface AppListViewController : UITableViewController {

	UITableView* _tableView;
	NSArray* _appList;

}

@property (nonatomic,retain) NSArray * appList;                    //@synthesize appList=_appList - In the implementation block
@property (nonatomic,retain) UITableView * tableView;              //@synthesize tableView=_tableView - In the implementation block
-(void)setAppList:(NSArray *)arg1 ;
-(NSArray *)appList;
-(id)init;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(void)didReceiveMemoryWarning;
-(void)setTableView:(UITableView *)arg1 ;
-(void)viewDidLoad;
-(UITableView *)tableView;
@end

