/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/ASIAutorotatingViewController.h>
#import <UIKit/UIActionSheetDelegate.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>

@class ASIHTTPRequest, UITableView, UIViewController;

@interface ASIAuthenticationDialog : ASIAutorotatingViewController <UIActionSheetDelegate, UITableViewDelegate, UITableViewDataSource> {

	ASIHTTPRequest* request;
	int type;
	UITableView* tableView;
	UIViewController* presentingController;
	char didEnableRotationNotifications;

}

@property (retain) ASIHTTPRequest * request; 
@property (assign) int type; 
@property (assign) char didEnableRotationNotifications; 
@property (nonatomic,retain) UIViewController * presentingController; 
@property (retain) UITableView * tableView; 
+(void)presentAuthenticationDialogForRequest:(id)arg1 ;
+(void)initialize;
+(void)dismiss;
-(void)setDidEnableRotationNotifications:(char)arg1 ;
-(char)didEnableRotationNotifications;
-(void)showTitle;
-(id)textFieldInRow:(unsigned)arg1 section:(unsigned)arg2 ;
-(void)presentNextDialog;
-(void)cancelAuthenticationFromDialog:(id)arg1 ;
-(void)loginWithCredentialsFromDialog:(id)arg1 ;
-(UIViewController *)presentingController;
-(id)requestsRequiringTheseCredentials;
-(id)domainField;
-(void)setPresentingController:(UIViewController *)arg1 ;
-(void)orientationChanged:(id)arg1 ;
-(id)usernameField;
-(void)setRequest:(ASIHTTPRequest *)arg1 ;
-(void)dealloc;
-(id)init;
-(float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2 ;
-(float)tableView:(id)arg1 heightForFooterInSection:(int)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2 ;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2 ;
-(void)show;
-(void)setType:(int)arg1 ;
-(int)type;
-(void)setTableView:(UITableView *)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(void)dismiss;
-(ASIHTTPRequest *)request;
-(UITableView *)tableView;
-(id)passwordField;
-(void)keyboardWillShow:(id)arg1 ;
@end

