/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/ASICloudFilesRequest.h>

@class NSString, ASICloudFilesContainer, ASICloudFilesContainerXMLParserDelegate;

@interface ASICloudFilesContainerRequest : ASICloudFilesRequest {

	NSString* currentContent;
	NSString* currentElement;
	ASICloudFilesContainer* currentObject;
	ASICloudFilesContainerXMLParserDelegate* xmlParserDelegate;

}

@property (retain) NSString * currentElement; 
@property (retain) NSString * currentContent; 
@property (retain) ASICloudFilesContainer * currentObject; 
@property (retain) ASICloudFilesContainerXMLParserDelegate * xmlParserDelegate; 
+(id)storageRequestWithMethod:(id)arg1 containerName:(id)arg2 queryString:(id)arg3 ;
+(id)storageRequestWithMethod:(id)arg1 queryString:(id)arg2 ;
+(id)storageRequestWithMethod:(id)arg1 ;
+(id)accountInfoRequest;
+(id)listRequestWithLimit:(unsigned)arg1 marker:(id)arg2 ;
+(id)listRequest;
+(id)createContainerRequest:(id)arg1 ;
+(id)deleteContainerRequest:(id)arg1 ;
-(unsigned)containerCount;
-(unsigned)bytesUsed;
-(NSString *)currentElement;
-(void)setCurrentElement:(NSString *)arg1 ;
-(NSString *)currentContent;
-(void)setCurrentContent:(NSString *)arg1 ;
-(ASICloudFilesContainer *)currentObject;
-(void)setCurrentObject:(ASICloudFilesContainer *)arg1 ;
-(ASICloudFilesContainerXMLParserDelegate *)xmlParserDelegate;
-(void)setXmlParserDelegate:(ASICloudFilesContainerXMLParserDelegate *)arg1 ;
-(void)dealloc;
-(id)containers;
@end

