/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSDate, NSData, NSMutableDictionary;

@interface ASICloudFilesObject : NSObject {

	NSString* name;
	NSString* hash;
	unsigned bytes;
	NSString* contentType;
	NSDate* lastModified;
	NSData* data;
	NSMutableDictionary* metadata;

}

@property (retain) NSString * name; 
@property (retain) NSString * hash; 
@property (assign) unsigned bytes; 
@property (retain) NSString * contentType; 
@property (retain) NSDate * lastModified; 
@property (retain) NSData * data; 
@property (retain) NSMutableDictionary * metadata; 
+(id)object;
-(void)setBytes:(unsigned)arg1 ;
-(void)setHash:(NSString *)arg1 ;
-(void)setLastModified:(NSDate *)arg1 ;
-(void)dealloc;
-(NSString *)hash;
-(unsigned)bytes;
-(NSData *)data;
-(void)setData:(NSData *)arg1 ;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(void)setContentType:(NSString *)arg1 ;
-(NSString *)contentType;
-(void)setMetadata:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)metadata;
-(NSDate *)lastModified;
@end

