/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface ASICloudFilesContainer : NSObject {

	NSString* name;
	unsigned count;
	unsigned bytes;
	char cdnEnabled;
	unsigned ttl;
	NSString* cdnURL;
	char logRetention;
	NSString* referrerACL;
	NSString* useragentACL;

}

@property (retain) NSString * name; 
@property (assign) unsigned count; 
@property (assign) unsigned bytes; 
@property (assign) char cdnEnabled; 
@property (assign) unsigned ttl; 
@property (retain) NSString * cdnURL; 
@property (assign) char logRetention; 
@property (retain) NSString * referrerACL; 
@property (retain) NSString * useragentACL; 
+(id)container;
-(char)cdnEnabled;
-(void)setCdnEnabled:(char)arg1 ;
-(unsigned)ttl;
-(void)setTtl:(unsigned)arg1 ;
-(NSString *)cdnURL;
-(void)setCdnURL:(NSString *)arg1 ;
-(char)logRetention;
-(void)setLogRetention:(char)arg1 ;
-(NSString *)referrerACL;
-(void)setReferrerACL:(NSString *)arg1 ;
-(NSString *)useragentACL;
-(void)setUseragentACL:(NSString *)arg1 ;
-(void)setBytes:(unsigned)arg1 ;
-(void)dealloc;
-(unsigned)count;
-(unsigned)bytes;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(void)setCount:(unsigned)arg1 ;
@end

