/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <CoreDAV/NSXMLParserDelegate.h>

@class NSMutableArray, NSString, ASICloudFilesContainer;

@interface ASICloudFilesContainerXMLParserDelegate : NSObject <NSXMLParserDelegate> {

	NSMutableArray* containerObjects;
	NSString* currentContent;
	NSString* currentElement;
	ASICloudFilesContainer* currentObject;

}

@property (retain) NSMutableArray * containerObjects; 
@property (retain) NSString * currentElement; 
@property (retain) NSString * currentContent; 
@property (retain) ASICloudFilesContainer * currentObject; 
-(NSMutableArray *)containerObjects;
-(NSString *)currentElement;
-(void)setCurrentElement:(NSString *)arg1 ;
-(NSString *)currentContent;
-(void)setCurrentContent:(NSString *)arg1 ;
-(ASICloudFilesContainer *)currentObject;
-(void)setCurrentObject:(ASICloudFilesContainer *)arg1 ;
-(void)setContainerObjects:(NSMutableArray *)arg1 ;
-(void)parser:(id)arg1 foundCharacters:(id)arg2 ;
-(void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 ;
-(void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5 ;
-(void)dealloc;
@end

