/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/ASICloudFilesRequest.h>

@class NSString, ASICloudFilesContainerXMLParserDelegate;

@interface ASICloudFilesCDNRequest : ASICloudFilesRequest {

	NSString* accountName;
	NSString* containerName;
	ASICloudFilesContainerXMLParserDelegate* xmlParserDelegate;

}

@property (retain) NSString * accountName; 
@property (retain) NSString * containerName; 
@property (retain) ASICloudFilesContainerXMLParserDelegate * xmlParserDelegate; 
+(id)cdnRequestWithMethod:(id)arg1 containerName:(id)arg2 ;
+(id)cdnRequestWithMethod:(id)arg1 query:(id)arg2 ;
+(id)listRequestWithLimit:(unsigned)arg1 marker:(id)arg2 enabledOnly:(char)arg3 ;
+(id)putRequestWithContainer:(id)arg1 ;
+(id)putRequestWithContainer:(id)arg1 ttl:(unsigned)arg2 ;
+(id)postRequestWithContainer:(id)arg1 ;
+(id)postRequestWithContainer:(id)arg1 cdnEnabled:(char)arg2 ttl:(unsigned)arg3 ;
+(id)listRequest;
+(id)containerInfoRequest:(id)arg1 ;
-(char)cdnEnabled;
-(id)cdnURI;
-(id)cdnSSLURI;
-(unsigned)cdnTTL;
-(ASICloudFilesContainerXMLParserDelegate *)xmlParserDelegate;
-(void)setXmlParserDelegate:(ASICloudFilesContainerXMLParserDelegate *)arg1 ;
-(void)dealloc;
-(void)setAccountName:(NSString *)arg1 ;
-(NSString *)accountName;
-(id)containers;
-(NSString *)containerName;
-(void)setContainerName:(NSString *)arg1 ;
@end

