/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:26 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol ASICacheDelegate <NSObject>
@required
-(void)clearCachedResponsesForStoragePolicy:(int)arg1;
-(id)pathToStoreCachedResponseHeadersForRequest:(id)arg1;
-(id)expiryDateForRequest:(id)arg1 maxAge:(double)arg2;
-(id)pathToStoreCachedResponseDataForRequest:(id)arg1;
-(id)pathToCachedResponseHeadersForURL:(id)arg1;
-(id)pathToCachedResponseDataForURL:(id)arg1;
-(void)removeCachedDataForURL:(id)arg1;
-(id)cachedResponseHeadersForURL:(id)arg1;
-(char)isCachedDataCurrentForRequest:(id)arg1;
-(int)defaultCachePolicy;
-(void)updateExpiryForRequest:(id)arg1 maxAge:(double)arg2;
-(char)canUseCachedDataForRequest:(id)arg1;
-(void)removeCachedDataForRequest:(id)arg1;
-(void)storeResponseForRequest:(id)arg1 maxAge:(double)arg2;
-(id)cachedResponseDataForURL:(id)arg1;

@end

