/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/ASICloudFilesRequest.h>
#import <CoreDAV/NSXMLParserDelegate.h>

@class NSString, ASICloudFilesObject, NSMutableArray;

@interface ASICloudFilesObjectRequest : ASICloudFilesRequest <NSXMLParserDelegate> {

	NSString* accountName;
	NSString* containerName;
	NSString* currentContent;
	NSString* currentElement;
	ASICloudFilesObject* currentObject;
	NSMutableArray* objects;

}

@property (retain) NSString * accountName; 
@property (retain) NSString * containerName; 
@property (retain) NSString * currentElement; 
@property (retain) NSString * currentContent; 
@property (retain) ASICloudFilesObject * currentObject; 
+(id)storageRequestWithMethod:(id)arg1 containerName:(id)arg2 queryString:(id)arg3 ;
+(id)storageRequestWithMethod:(id)arg1 containerName:(id)arg2 ;
+(id)storageRequestWithMethod:(id)arg1 containerName:(id)arg2 objectPath:(id)arg3 ;
+(id)queryStringWithContainer:(id)arg1 limit:(unsigned)arg2 marker:(id)arg3 prefix:(id)arg4 path:(id)arg5 ;
+(id)listRequestWithContainer:(id)arg1 limit:(unsigned)arg2 marker:(id)arg3 prefix:(id)arg4 path:(id)arg5 ;
+(id)putObjectRequestWithContainer:(id)arg1 objectPath:(id)arg2 contentType:(id)arg3 objectData:(id)arg4 metadata:(id)arg5 etag:(id)arg6 ;
+(id)postObjectRequestWithContainer:(id)arg1 objectPath:(id)arg2 metadata:(id)arg3 ;
+(id)containerInfoRequest:(id)arg1 ;
+(id)objectInfoRequest:(id)arg1 objectPath:(id)arg2 ;
+(id)listRequestWithContainer:(id)arg1 ;
+(id)getObjectRequestWithContainer:(id)arg1 objectPath:(id)arg2 ;
+(id)putObjectRequestWithContainer:(id)arg1 object:(id)arg2 ;
+(id)putObjectRequestWithContainer:(id)arg1 objectPath:(id)arg2 contentType:(id)arg3 file:(id)arg4 metadata:(id)arg5 etag:(id)arg6 ;
+(id)postObjectRequestWithContainer:(id)arg1 object:(id)arg2 ;
+(id)deleteObjectRequestWithContainer:(id)arg1 objectPath:(id)arg2 ;
-(NSString *)currentElement;
-(void)setCurrentElement:(NSString *)arg1 ;
-(NSString *)currentContent;
-(void)setCurrentContent:(NSString *)arg1 ;
-(ASICloudFilesObject *)currentObject;
-(void)setCurrentObject:(ASICloudFilesObject *)arg1 ;
-(unsigned)containerObjectCount;
-(unsigned)containerBytesUsed;
-(id)objects;
-(void)parser:(id)arg1 foundCharacters:(id)arg2 ;
-(void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 ;
-(void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5 ;
-(void)dealloc;
-(id)object;
-(void)setAccountName:(NSString *)arg1 ;
-(NSString *)accountName;
-(NSString *)containerName;
-(void)setContainerName:(NSString *)arg1 ;
@end

