/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:26 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/ASICacheDelegate.h>

@class NSString, NSRecursiveLock;

@interface ASIDownloadCache : NSObject <ASICacheDelegate> {

	int defaultCachePolicy;
	NSString* storagePath;
	NSRecursiveLock* accessLock;
	char shouldRespectCacheControlHeaders;

}

@property (assign,nonatomic) int defaultCachePolicy; 
@property (nonatomic,retain) NSString * storagePath; 
@property (retain) NSRecursiveLock * accessLock; 
@property (assign) char shouldRespectCacheControlHeaders; 
+(char)serverAllowsResponseCachingForRequest:(id)arg1 ;
+(id)fileExtensionsToHandleAsHTML;
+(id)keyForURL:(id)arg1 ;
+(id)sharedCache;
+(void)initialize;
-(void)setShouldRespectCacheControlHeaders:(char)arg1 ;
-(void)setDefaultCachePolicy:(int)arg1 ;
-(void)setAccessLock:(NSRecursiveLock *)arg1 ;
-(NSRecursiveLock *)accessLock;
-(void)clearCachedResponsesForStoragePolicy:(int)arg1 ;
-(id)pathToStoreCachedResponseHeadersForRequest:(id)arg1 ;
-(id)expiryDateForRequest:(id)arg1 maxAge:(double)arg2 ;
-(char)shouldRespectCacheControlHeaders;
-(id)pathToStoreCachedResponseDataForRequest:(id)arg1 ;
-(id)pathToCachedResponseHeadersForURL:(id)arg1 ;
-(id)pathToCachedResponseDataForURL:(id)arg1 ;
-(id)pathToFile:(id)arg1 ;
-(void)removeCachedDataForURL:(id)arg1 ;
-(id)cachedResponseHeadersForURL:(id)arg1 ;
-(char)isCachedDataCurrentForRequest:(id)arg1 ;
-(int)defaultCachePolicy;
-(void)updateExpiryForRequest:(id)arg1 maxAge:(double)arg2 ;
-(char)canUseCachedDataForRequest:(id)arg1 ;
-(void)removeCachedDataForRequest:(id)arg1 ;
-(void)storeResponseForRequest:(id)arg1 maxAge:(double)arg2 ;
-(id)cachedResponseDataForURL:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)setStoragePath:(NSString *)arg1 ;
-(NSString *)storagePath;
@end

