/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:26 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <AutoTouch/ASIHTTPRequest.h>
#import <CoreFoundation/NSCopying.h>

@class NSMutableArray;

@interface ASIFormDataRequest : ASIHTTPRequest <NSCopying> {

	NSMutableArray* postData;
	NSMutableArray* fileData;
	int postFormat;
	unsigned stringEncoding;

}

@property (assign) int postFormat; 
@property (assign) unsigned stringEncoding; 
@property (retain) NSMutableArray * postData; 
@property (retain) NSMutableArray * fileData; 
+(id)requestWithURL:(id)arg1 ;
-(void)setPostValue:(id)arg1 forKey:(id)arg2 ;
-(void)setFile:(id)arg1 withFileName:(id)arg2 andContentType:(id)arg3 forKey:(id)arg4 ;
-(NSMutableArray *)postData;
-(unsigned)stringEncoding;
-(void)setPostFormat:(int)arg1 ;
-(void)setStringEncoding:(unsigned)arg1 ;
-(void)setPostData:(NSMutableArray *)arg1 ;
-(void)addPostValue:(id)arg1 forKey:(id)arg2 ;
-(void)addFile:(id)arg1 withFileName:(id)arg2 andContentType:(id)arg3 forKey:(id)arg4 ;
-(void)addData:(id)arg1 withFileName:(id)arg2 andContentType:(id)arg3 forKey:(id)arg4 ;
-(void)setData:(id)arg1 withFileName:(id)arg2 andContentType:(id)arg3 forKey:(id)arg4 ;
-(int)postFormat;
-(void)buildURLEncodedPostBody;
-(void)buildMultipartFormDataPostBody;
-(void)appendPostString:(id)arg1 ;
-(id)encodeURL:(id)arg1 ;
-(void)addFile:(id)arg1 forKey:(id)arg2 ;
-(void)setFile:(id)arg1 forKey:(id)arg2 ;
-(void)addData:(id)arg1 forKey:(id)arg2 ;
-(void)buildPostBody;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)initWithURL:(id)arg1 ;
-(NSMutableArray *)fileData;
-(void)setFileData:(NSMutableArray *)arg1 ;
-(void)setData:(id)arg1 forKey:(id)arg2 ;
@end

