/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol ASIHTTPRequestDelegate <NSObject>
@optional
-(void)authenticationNeededForRequest:(id)arg1;
-(void)proxyAuthenticationNeededForRequest:(id)arg1;
-(void)request:(id)arg1 willRedirectToURL:(id)arg2;
-(void)requestStarted:(id)arg1;
-(void)request:(id)arg1 didReceiveResponseHeaders:(id)arg2;
-(void)requestFinished:(id)arg1;
-(void)requestFailed:(id)arg1;
-(void)requestRedirected:(id)arg1;
-(void)request:(id)arg1 didReceiveData:(id)arg2;

@end

