/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSInputStream, ASIHTTPRequest;

@interface ASIInputStream : NSObject {

	NSInputStream* stream;
	ASIHTTPRequest* request;

}

@property (nonatomic,retain) NSInputStream * stream; 
@property (assign,nonatomic) ASIHTTPRequest * request; 
+(id)inputStreamWithFileAtPath:(id)arg1 request:(id)arg2 ;
+(id)inputStreamWithData:(id)arg1 request:(id)arg2 ;
+(void)initialize;
-(void)setStream:(NSInputStream *)arg1 ;
-(id)propertyForKey:(id)arg1 ;
-(char)setProperty:(id)arg1 forKey:(id)arg2 ;
-(void)scheduleInRunLoop:(id)arg1 forMode:(id)arg2 ;
-(void)removeFromRunLoop:(id)arg1 forMode:(id)arg2 ;
-(unsigned)streamStatus;
-(id)streamError;
-(int)read:(char*)arg1 maxLength:(unsigned)arg2 ;
-(void)setRequest:(ASIHTTPRequest *)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)delegate;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(void)forwardInvocation:(id)arg1 ;
-(void)close;
-(ASIHTTPRequest *)request;
-(NSInputStream *)stream;
-(void)open;
@end

