/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <Foundation/NSOperationQueue.h>
#import <AutoTouch/ASIProgressDelegate.h>
#import <AutoTouch/ASIHTTPRequestDelegate.h>
#import <CoreFoundation/NSCopying.h>

@class NSDictionary;

@interface ASINetworkQueue : NSOperationQueue <ASIProgressDelegate, ASIHTTPRequestDelegate, NSCopying> {

	id delegate;
	SEL requestDidStartSelector;
	SEL requestDidReceiveResponseHeadersSelector;
	SEL requestWillRedirectSelector;
	SEL requestDidFinishSelector;
	SEL requestDidFailSelector;
	SEL queueDidFinishSelector;
	id uploadProgressDelegate;
	unsigned long long bytesUploadedSoFar;
	unsigned long long totalBytesToUpload;
	id downloadProgressDelegate;
	unsigned long long bytesDownloadedSoFar;
	unsigned long long totalBytesToDownload;
	char shouldCancelAllRequestsOnFailure;
	int requestsCount;
	char showAccurateProgress;
	NSDictionary* userInfo;

}

@property (assign,setter=setUploadProgressDelegate:,nonatomic) id uploadProgressDelegate; 
@property (assign,setter=setDownloadProgressDelegate:,nonatomic) id downloadProgressDelegate; 
@property (assign) SEL requestDidStartSelector; 
@property (assign) SEL requestDidReceiveResponseHeadersSelector; 
@property (assign) SEL requestWillRedirectSelector; 
@property (assign) SEL requestDidFinishSelector; 
@property (assign) SEL requestDidFailSelector; 
@property (assign) SEL queueDidFinishSelector; 
@property (assign) char shouldCancelAllRequestsOnFailure; 
@property (assign) id delegate; 
@property (assign) char showAccurateProgress; 
@property (assign) int requestsCount; 
@property (retain) NSDictionary * userInfo; 
@property (assign) unsigned long long bytesUploadedSoFar; 
@property (assign) unsigned long long totalBytesToUpload; 
@property (assign) unsigned long long bytesDownloadedSoFar; 
@property (assign) unsigned long long totalBytesToDownload; 
+(id)queue;
-(void)setShouldCancelAllRequestsOnFailure:(char)arg1 ;
-(void)setDownloadProgressDelegate:(id)arg1 ;
-(void)setUploadProgressDelegate:(id)arg1 ;
-(void)setRequestDidStartSelector:(SEL)arg1 ;
-(void)setRequestDidReceiveResponseHeadersSelector:(SEL)arg1 ;
-(void)setRequestDidFailSelector:(SEL)arg1 ;
-(void)setRequestDidFinishSelector:(SEL)arg1 ;
-(void)setQueueDidFinishSelector:(SEL)arg1 ;
-(void)setBytesUploadedSoFar:(unsigned long long)arg1 ;
-(void)setTotalBytesToUpload:(unsigned long long)arg1 ;
-(void)setBytesDownloadedSoFar:(unsigned long long)arg1 ;
-(void)setTotalBytesToDownload:(unsigned long long)arg1 ;
-(void)resetProgressDelegate:(id*)arg1 ;
-(void)setShowAccurateProgress:(char)arg1 ;
-(int)requestsCount;
-(void)setRequestsCount:(int)arg1 ;
-(char)showAccurateProgress;
-(void)addHEADOperation:(id)arg1 ;
-(void)request:(id)arg1 incrementUploadSizeBy:(long long)arg2 ;
-(void)request:(id)arg1 incrementDownloadSizeBy:(long long)arg2 ;
-(SEL)requestDidStartSelector;
-(SEL)requestDidReceiveResponseHeadersSelector;
-(SEL)requestWillRedirectSelector;
-(SEL)requestDidFinishSelector;
-(SEL)queueDidFinishSelector;
-(SEL)requestDidFailSelector;
-(char)shouldCancelAllRequestsOnFailure;
-(unsigned long long)bytesDownloadedSoFar;
-(id)downloadProgressDelegate;
-(unsigned long long)totalBytesToDownload;
-(unsigned long long)bytesUploadedSoFar;
-(id)uploadProgressDelegate;
-(unsigned long long)totalBytesToUpload;
-(void)authenticationNeededForRequest:(id)arg1 ;
-(void)proxyAuthenticationNeededForRequest:(id)arg1 ;
-(void)request:(id)arg1 willRedirectToURL:(id)arg2 ;
-(void)setRequestWillRedirectSelector:(SEL)arg1 ;
-(void)request:(id)arg1 didReceiveBytes:(long long)arg2 ;
-(void)request:(id)arg1 didSendBytes:(long long)arg2 ;
-(void)requestStarted:(id)arg1 ;
-(void)request:(id)arg1 didReceiveResponseHeaders:(id)arg2 ;
-(void)requestFinished:(id)arg1 ;
-(void)requestFailed:(id)arg1 ;
-(void)go;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(char)respondsToSelector:(SEL)arg1 ;
-(id)init;
-(id)delegate;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSDictionary *)userInfo;
-(void)cancelAllOperations;
-(void)reset;
-(void)addOperation:(id)arg1 ;
-(void)setUserInfo:(NSDictionary *)arg1 ;
-(void)setSuspended:(char)arg1 ;
@end

