/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol ASIProgressDelegate <NSObject>
@optional
-(void)request:(id)arg1 incrementUploadSizeBy:(long long)arg2;
-(void)request:(id)arg1 incrementDownloadSizeBy:(long long)arg2;
-(void)request:(id)arg1 didReceiveBytes:(long long)arg2;
-(void)request:(id)arg1 didSendBytes:(long long)arg2;
-(void)setProgress:(float)arg1;

@end

