/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <AutoTouch/ASIHTTPRequest.h>
#import <CoreFoundation/NSCopying.h>
#import <CoreDAV/NSXMLParserDelegate.h>

@class NSString, NSMutableArray;

@interface ASIS3Request : ASIHTTPRequest <NSCopying, NSXMLParserDelegate> {

	NSString* accessKey;
	NSString* secretAccessKey;
	NSString* requestScheme;
	NSString* dateString;
	NSString* accessPolicy;
	NSString* currentXMLElementContent;
	NSMutableArray* currentXMLElementStack;

}

@property (retain) NSString * dateString; 
@property (retain) NSString * accessKey; 
@property (retain) NSString * secretAccessKey; 
@property (retain) NSString * accessPolicy; 
@property (retain) NSString * currentXMLElementContent; 
@property (retain) NSMutableArray * currentXMLElementStack; 
@property (retain) NSString * requestScheme; 
+(id)S3Host;
+(id)S3ResponseDateFormatter;
+(id)S3RequestDateFormatter;
+(id)sharedAccessKey;
+(id)sharedSecretAccessKey;
+(id)HMACSHA1withKey:(id)arg1 forString:(id)arg2 ;
+(void)setSharedAccessKey:(id)arg1 ;
+(void)setSharedSecretAccessKey:(id)arg1 ;
+(id)stringByURLEncodingForS3Path:(id)arg1 ;
-(NSString *)requestScheme;
-(NSString *)currentXMLElementContent;
-(NSMutableArray *)currentXMLElementStack;
-(id)canonicalizedResource;
-(void)buildURL;
-(void)setRequestScheme:(NSString *)arg1 ;
-(id)HEADRequest;
-(NSString *)secretAccessKey;
-(void)setSecretAccessKey:(NSString *)arg1 ;
-(NSString *)accessPolicy;
-(void)buildRequestHeaders;
-(id)S3Headers;
-(id)stringToSignForHeaders:(id)arg1 resource:(id)arg2 ;
-(void)parseResponseXML;
-(void)requestFinished;
-(void)setCurrentXMLElementStack:(NSMutableArray *)arg1 ;
-(void)setCurrentXMLElementContent:(NSString *)arg1 ;
-(void)setAccessPolicy:(NSString *)arg1 ;
-(void)parser:(id)arg1 parseErrorOccurred:(id)arg2 ;
-(void)parser:(id)arg1 foundCharacters:(id)arg2 ;
-(void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 ;
-(void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5 ;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setDate:(id)arg1 ;
-(void)main;
-(id)initWithURL:(id)arg1 ;
-(void)setDateString:(NSString *)arg1 ;
-(NSString *)dateString;
-(NSString *)accessKey;
-(void)setAccessKey:(NSString *)arg1 ;
@end

