/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <CoreFoundation/NSCopying.h>

@class NSString, NSDate;

@interface ASIS3BucketObject : NSObject <NSCopying> {

	NSString* bucket;
	NSString* key;
	NSDate* lastModified;
	NSString* ETag;
	unsigned long long size;
	NSString* ownerID;
	NSString* ownerName;

}

@property (retain) NSString * bucket; 
@property (retain) NSString * key; 
@property (retain) NSDate * lastModified; 
@property (retain) NSString * ETag; 
@property (assign) unsigned long long size; 
@property (retain) NSString * ownerID; 
@property (retain) NSString * ownerName; 
+(id)objectWithBucket:(id)arg1 ;
-(NSString *)ETag;
-(NSString *)ownerName;
-(void)setETag:(NSString *)arg1 ;
-(void)setOwnerID:(NSString *)arg1 ;
-(void)setOwnerName:(NSString *)arg1 ;
-(id)GETRequest;
-(id)PUTRequestWithFile:(id)arg1 ;
-(id)DELETERequest;
-(NSString *)ownerID;
-(void)setLastModified:(NSDate *)arg1 ;
-(void)setBucket:(NSString *)arg1 ;
-(NSString *)bucket;
-(void)dealloc;
-(unsigned long long)size;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setSize:(unsigned long long)arg1 ;
-(NSString *)key;
-(void)setKey:(NSString *)arg1 ;
-(NSDate *)lastModified;
@end

