/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <AutoTouch/ASIS3Request.h>

@class NSString;

@interface ASIS3ObjectRequest : ASIS3Request {

	NSString* bucket;
	NSString* key;
	NSString* sourceBucket;
	NSString* sourceKey;
	NSString* mimeType;
	NSString* subResource;
	NSString* storageClass;

}

@property (nonatomic,retain) NSString * bucket; 
@property (nonatomic,retain) NSString * key; 
@property (nonatomic,retain) NSString * sourceBucket; 
@property (nonatomic,retain) NSString * sourceKey; 
@property (nonatomic,retain) NSString * mimeType; 
@property (nonatomic,retain) NSString * subResource; 
@property (nonatomic,retain) NSString * storageClass; 
+(id)requestWithBucket:(id)arg1 key:(id)arg2 ;
+(id)PUTRequestForFile:(id)arg1 withBucket:(id)arg2 key:(id)arg3 ;
+(id)requestWithBucket:(id)arg1 key:(id)arg2 subResource:(id)arg3 ;
+(id)PUTRequestForData:(id)arg1 withBucket:(id)arg2 key:(id)arg3 ;
+(id)DELETERequestWithBucket:(id)arg1 key:(id)arg2 ;
+(id)COPYRequestFromBucket:(id)arg1 key:(id)arg2 toBucket:(id)arg3 key:(id)arg4 ;
+(id)HEADRequestWithBucket:(id)arg1 key:(id)arg2 ;
-(void)setSubResource:(NSString *)arg1 ;
-(NSString *)subResource;
-(id)canonicalizedResource;
-(void)buildURL;
-(void)setSourceBucket:(NSString *)arg1 ;
-(void)setSourceKey:(NSString *)arg1 ;
-(NSString *)sourceBucket;
-(NSString *)sourceKey;
-(NSString *)storageClass;
-(void)setStorageClass:(NSString *)arg1 ;
-(id)HEADRequest;
-(id)S3Headers;
-(id)stringToSignForHeaders:(id)arg1 resource:(id)arg2 ;
-(void)setBucket:(NSString *)arg1 ;
-(NSString *)bucket;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)key;
-(NSString *)mimeType;
-(void)setKey:(NSString *)arg1 ;
-(void)setMimeType:(NSString *)arg1 ;
@end

