/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <AutoTouch/ASIS3Request.h>

@class NSString, ASIS3BucketObject, NSMutableArray;

@interface ASIS3BucketRequest : ASIS3Request {

	NSString* bucket;
	NSString* subResource;
	NSString* prefix;
	NSString* marker;
	int maxResultCount;
	NSString* delimiter;
	ASIS3BucketObject* currentObject;
	NSMutableArray* objects;
	NSMutableArray* commonPrefixes;
	char isTruncated;

}

@property (nonatomic,retain) NSString * bucket; 
@property (nonatomic,retain) NSString * subResource; 
@property (nonatomic,retain) NSString * prefix; 
@property (nonatomic,retain) NSString * marker; 
@property (assign,nonatomic) int maxResultCount; 
@property (nonatomic,retain) NSString * delimiter; 
@property (retain) NSMutableArray * objects; 
@property (retain) NSMutableArray * commonPrefixes; 
@property (assign) char isTruncated; 
@property (nonatomic,retain) ASIS3BucketObject * currentObject; 
+(id)requestWithBucket:(id)arg1 ;
+(id)requestWithBucket:(id)arg1 subResource:(id)arg2 ;
+(id)PUTRequestWithBucket:(id)arg1 ;
+(id)DELETERequestWithBucket:(id)arg1 ;
-(ASIS3BucketObject *)currentObject;
-(void)setCurrentObject:(ASIS3BucketObject *)arg1 ;
-(void)setCommonPrefixes:(NSMutableArray *)arg1 ;
-(void)setSubResource:(NSString *)arg1 ;
-(NSString *)subResource;
-(NSString *)delimiter;
-(int)maxResultCount;
-(NSMutableArray *)commonPrefixes;
-(void)setIsTruncated:(char)arg1 ;
-(void)setMaxResultCount:(int)arg1 ;
-(void)setDelimiter:(NSString *)arg1 ;
-(id)canonicalizedResource;
-(void)buildURL;
-(char)isTruncated;
-(NSMutableArray *)objects;
-(void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 ;
-(void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5 ;
-(void)setBucket:(NSString *)arg1 ;
-(NSString *)bucket;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)initWithURL:(id)arg1 ;
-(NSString *)marker;
-(void)setMarker:(NSString *)arg1 ;
-(NSString *)prefix;
-(void)setPrefix:(NSString *)arg1 ;
-(void)setObjects:(NSMutableArray *)arg1 ;
@end

