/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/ASIS3Request.h>

@class ASIS3Bucket, NSString, NSMutableArray;

@interface ASIS3ServiceRequest : ASIS3Request {

	ASIS3Bucket* currentBucket;
	NSString* ownerName;
	NSString* ownerID;
	NSMutableArray* buckets;

}

@property (retain) NSMutableArray * buckets; 
@property (nonatomic,retain) ASIS3Bucket * currentBucket; 
@property (nonatomic,retain) NSString * ownerID; 
@property (nonatomic,retain) NSString * ownerName; 
+(id)serviceRequest;
-(NSString *)ownerName;
-(void)setOwnerID:(NSString *)arg1 ;
-(void)setOwnerName:(NSString *)arg1 ;
-(void)buildURL;
-(void)setBuckets:(NSMutableArray *)arg1 ;
-(void)setCurrentBucket:(ASIS3Bucket *)arg1 ;
-(ASIS3Bucket *)currentBucket;
-(NSString *)ownerID;
-(void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 ;
-(void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5 ;
-(NSMutableArray *)buckets;
-(void)dealloc;
-(id)initWithURL:(id)arg1 ;
@end

