/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSDate;

@interface ASIS3Bucket : NSObject {

	NSString* name;
	NSDate* creationDate;
	NSString* ownerID;
	NSString* ownerName;

}

@property (retain) NSString * name; 
@property (retain) NSDate * creationDate; 
@property (retain) NSString * ownerID; 
@property (retain) NSString * ownerName; 
+(id)bucketWithOwnerID:(id)arg1 ownerName:(id)arg2 ;
-(NSString *)ownerName;
-(void)setOwnerID:(NSString *)arg1 ;
-(void)setOwnerName:(NSString *)arg1 ;
-(NSString *)ownerID;
-(void)dealloc;
-(id)description;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(NSDate *)creationDate;
-(void)setCreationDate:(NSDate *)arg1 ;
@end

