/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <AutoTouch/ASIHTTPRequest.h>

@class ASINetworkQueue, NSMutableDictionary;

@interface ASIWebPageRequest : ASIHTTPRequest {

	ASINetworkQueue* externalResourceQueue;
	NSMutableDictionary* resourceList;
	xmlDoc* doc;
	int webContentType;
	ASIWebPageRequest* parentRequest;
	int urlReplacementMode;
	char shouldIgnoreExternalResourceErrors;

}

@property (nonatomic,retain) ASIWebPageRequest * parentRequest; 
@property (assign,nonatomic) int urlReplacementMode; 
@property (assign,nonatomic) char shouldIgnoreExternalResourceErrors; 
@property (nonatomic,retain) ASINetworkQueue * externalResourceQueue; 
@property (nonatomic,retain) NSMutableDictionary * resourceList; 
+(id)CSSURLsFromString:(id)arg1 ;
+(void)initialize;
-(void)requestFinished;
-(void)setShouldIgnoreExternalResourceErrors:(char)arg1 ;
-(void)parseAsHTML;
-(void)parseAsCSS;
-(void)setResourceList:(NSMutableDictionary *)arg1 ;
-(void)addURLToFetch:(id)arg1 ;
-(NSMutableDictionary *)resourceList;
-(ASINetworkQueue *)externalResourceQueue;
-(void)setExternalResourceQueue:(ASINetworkQueue *)arg1 ;
-(char)shouldIgnoreExternalResourceErrors;
-(void)finishedFetchingExternalResources:(id)arg1 ;
-(void)externalResourceFetchSucceeded:(id)arg1 ;
-(void)externalResourceFetchFailed:(id)arg1 ;
-(void)setParentRequest:(ASIWebPageRequest *)arg1 ;
-(int)urlReplacementMode;
-(void)setUrlReplacementMode:(int)arg1 ;
-(id)cachePathForRequest:(id)arg1 ;
-(void)readResourceURLs;
-(id)contentForExternalURL:(id)arg1 ;
-(void)updateResourceURLs;
-(ASIWebPageRequest *)parentRequest;
-(id)relativePathTo:(id)arg1 fromPath:(id)arg2 ;
-(void)markAsFinished;
-(const char*)encodingName;
-(void)dealloc;
-(char)respondsToSelector:(SEL)arg1 ;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(void)forwardInvocation:(id)arg1 ;
-(id)initWithURL:(id)arg1 ;
@end

