/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableData, NSData;

@interface AsyncReadPacket : NSObject {

	NSMutableData* buffer;
	long bytesDone;
	double timeout;
	long maxLength;
	long tag;
	NSData* term;
	char readAllAvailableData;

}
-(id)initWithData:(id)arg1 timeout:(double)arg2 tag:(long)arg3 readAllAvailable:(char)arg4 terminator:(id)arg5 maxLength:(long)arg6 ;
-(void)dealloc;
@end

