/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:30 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

typedef struct __CFHTTPMessage* CFHTTPMessageRef;

typedef struct __CFSocket* CFSocketRef;

typedef struct __CFReadStream* CFReadStreamRef;

typedef struct __CFWriteStream* CFWriteStreamRef;

typedef struct __CFRunLoopSource* CFRunLoopSourceRef;

typedef struct __CFRunLoop* CFRunLoopRef;

typedef struct {
	int version;
	void info;
	/*function pointer*/void* retain;
	/*function pointer*/void* release;
	/*function pointer*/void* copyDescription;
} SCD_Struct_As6;

typedef struct {
	int field1;
	int field2;
} SCD_Struct_As7;

typedef struct __CFData* CFDataRef;

typedef struct z_stream_s {
	char* next_in;
	unsigned avail_in;
	unsigned total_in;
	char* next_out;
	unsigned avail_out;
	unsigned total_out;
	char* msg;
	internal_state state;
	/*function pointer*/void* zalloc;
	/*function pointer*/void* zfree;
	void opaque;
	int data_type;
	unsigned adler;
	unsigned reserved;
} z_stream_s;

typedef struct _NSZone* NSZoneRef;

typedef struct _CFHTTPAuthentication* CFHTTPAuthenticationRef;

typedef struct __SecIdentity* SecIdentityRef;

typedef struct CGContext* CGContextRef;

typedef struct CGPoint {
	float x;
	float y;
} CGPoint;

typedef struct sqlite3* sqlite3Ref;

typedef struct sqlite3_stmt* sqlite3_stmtRef;

typedef struct dispatch_queue_s* dispatch_queue_sRef;

typedef struct {
	unsigned long field1;
	id field2;
	unsigned long field3;
	unsigned long field4[5];
} SCD_Struct_JK18;

typedef struct CGAffineTransform {
	float a;
	float b;
	float c;
	float d;
	float tx;
	float ty;
} CGAffineTransform;

typedef struct CGSize {
	float width;
	float height;
} CGSize;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

typedef struct UIEdgeInsets {
	float top;
	float left;
	float bottom;
	float right;
} UIEdgeInsets;

typedef struct CATransform3D {
	float m11;
	float m12;
	float m13;
	float m14;
	float m21;
	float m22;
	float m23;
	float m24;
	float m31;
	float m32;
	float m33;
	float m34;
	float m41;
	float m42;
	float m43;
	float m44;
} CATransform3D;

typedef struct _CCCryptor* CCCryptorRef;

typedef struct {
	unsigned ctx[96];
} SCD_Struct_RN25;

typedef struct RNCryptorKeyDerivationSettings {
	unsigned keySize;
	unsigned saltSize;
	unsigned PBKDFAlgorithm;
	unsigned PRF;
	unsigned rounds;
	char hasV2Password;
} RNCryptorKeyDerivationSettings;

typedef struct RNCryptorSettings {
	unsigned algorithm;
	unsigned blockSize;
	unsigned IVSize;
	unsigned options;
	unsigned HMACAlgorithm;
	unsigned HMACLength;
	RNCryptorKeyDerivationSettings keySettings;
	RNCryptorKeyDerivationSettings HMACKeySettings;
} RNCryptorSettings;

typedef struct __SCNetworkReachability* SCNetworkReachabilityRef;

