/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <QuartzCore/CALayer.h>

@class UIColor;

@interface DACircularProgressLayer : CALayer

@property (nonatomic,retain) UIColor * trackTintColor; 
@property (nonatomic,retain) UIColor * progressTintColor; 
@property (assign,nonatomic) int roundedCorners; 
@property (assign,nonatomic) float thicknessRatio; 
@property (assign,nonatomic) float progress; 
@property (assign,nonatomic) int clockwiseProgress; 
+(char)needsDisplayForKey:(id)arg1 ;
-(void)drawInContext:(CGContextRef)arg1 ;
@end

