/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UIColor;

@interface DACircularProgressView : UIView {

	float _indeterminateDuration;

}

@property (nonatomic,retain) UIColor * trackTintColor; 
@property (nonatomic,retain) UIColor * progressTintColor; 
@property (assign,nonatomic) int roundedCorners; 
@property (assign,nonatomic) float thicknessRatio; 
@property (assign,nonatomic) int clockwiseProgress; 
@property (assign,nonatomic) float progress; 
@property (assign,nonatomic) float indeterminateDuration;              //@synthesize indeterminateDuration=_indeterminateDuration - In the implementation block
@property (assign,nonatomic) int indeterminate; 
+(void)initialize;
+(Class)layerClass;
-(void)_UIAppearance_setIndeterminate:(int)arg1 ;
-(void)_UIAppearance_setIndeterminateDuration:(float)arg1 ;
-(void)_UIAppearance_setClockwiseProgress:(int)arg1 ;
-(void)_UIAppearance_setRoundedCorners:(int)arg1 ;
-(void)_UIAppearance_setThicknessRatio:(float)arg1 ;
-(void)_UIAppearance_setProgressTintColor:(id)arg1 ;
-(void)_UIAppearance_setTrackTintColor:(id)arg1 ;
-(int)clockwiseProgress;
-(float)thicknessRatio;
-(void)setThicknessRatio:(float)arg1 ;
-(void)setClockwiseProgress:(int)arg1 ;
-(void)setIndeterminateDuration:(float)arg1 ;
-(id)circularProgressLayer;
-(float)indeterminateDuration;
-(void)didMoveToWindow;
-(id)init;
-(void)setProgress:(float)arg1 ;
-(UIColor *)trackTintColor;
-(UIColor *)progressTintColor;
-(void)setProgressTintColor:(UIColor *)arg1 ;
-(void)setProgress:(float)arg1 animated:(char)arg2 ;
-(void)setTrackTintColor:(UIColor *)arg1 ;
-(float)progress;
-(void)setIndeterminate:(int)arg1 ;
-(int)roundedCorners;
-(void)setRoundedCorners:(int)arg1 ;
-(int)indeterminate;
@end

