/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface DataManager : NSObject
+(id)findPlaySettingsByScriptTitle:(id)arg1 ;
+(id)getActivatorTriggerByScriptTitle:(id)arg1 ;
+(char)updatePlaySettings:(id)arg1 ;
+(char)insertPlaySettings:(id)arg1 ;
+(char)deletePlaySettingsByScriptTitle:(id)arg1 ;
+(char)updateScriptTitleOfPlaySettingsFrom:(id)arg1 to:(id)arg2 ;
+(char)updateScriptTitleOfActivatorTriggerFrom:(id)arg1 to:(id)arg2 ;
+(id)getActivatorTriggerForControlPanel;
+(id)getActivatorTriggerForStartStopPlaying;
+(id)dataFilePath;
+(id)mapFMResultSetToActivatorTriggerArray:(id)arg1 ;
+(id)mapFMResultSetToPlaySettingsArray:(id)arg1 ;
+(char)initDb;
+(char)addActivatorTrigger:(id)arg1 ;
+(char)removeActivatorTrigger:(id)arg1 ;
+(char)removeActivatorTriggerByScriptTitle:(id)arg1 ;
+(id)getActivatorTriggersAll;
+(id)getActivatorTriggerByEventName:(id)arg1 ;
+(id)findAllPlaySettings;
+(int)countPlaySettings;
@end

