/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSFileHandle;

@interface DDFileReader : NSObject {

	NSString* filePath;
	NSFileHandle* fileHandle;
	unsigned long long currentOffset;
	unsigned long long totalFileLength;
	NSString* lineDelimiter;
	unsigned chunkSize;

}

@property (nonatomic,copy) NSString * lineDelimiter; 
@property (assign,nonatomic) unsigned chunkSize; 
-(id)readLine;
-(id)readTrimmedLine;
-(NSString *)lineDelimiter;
-(void)setLineDelimiter:(NSString *)arg1 ;
-(void)enumerateLinesUsingBlock:(/*^block*/id)arg1 ;
-(void)dealloc;
-(id)initWithFilePath:(id)arg1 ;
-(void)setChunkSize:(unsigned)arg1 ;
-(unsigned)chunkSize;
@end

