/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <UIKit/UIView.h>

@protocol DYRateViewDelegate;
@class UIImage, NSObject;

@interface DYRateView : UIView {

	UIImage* _fullStarImage;
	UIImage* _emptyStarImage;
	CGPoint _origin;
	int _numOfStars;
	char _editable;
	float _rate;
	int _alignment;
	float _padding;
	NSObject*<DYRateViewDelegate> _delegate;

}

@property (assign,nonatomic) int alignment;                                       //@synthesize alignment=_alignment - In the implementation block
@property (assign,nonatomic) float rate;                                          //@synthesize rate=_rate - In the implementation block
@property (assign,nonatomic) float padding;                                       //@synthesize padding=_padding - In the implementation block
@property (assign,nonatomic) char editable;                                       //@synthesize editable=_editable - In the implementation block
@property (nonatomic,retain) UIImage * fullStarImage;                             //@synthesize fullStarImage=_fullStarImage - In the implementation block
@property (nonatomic,retain) UIImage * emptyStarImage;                            //@synthesize emptyStarImage=_emptyStarImage - In the implementation block
@property (assign,nonatomic) NSObject*<DYRateViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id)initWithFrame:(CGRect)arg1 fullStar:(id)arg2 emptyStar:(id)arg3 ;
-(void)commonSetup;
-(void)notifyDelegate;
-(void)handleTouchAtLocation:(CGPoint)arg1 ;
-(UIImage *)fullStarImage;
-(void)setFullStarImage:(UIImage *)arg1 ;
-(UIImage *)emptyStarImage;
-(void)setEmptyStarImage:(UIImage *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)drawRect:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setDelegate:(NSObject*<DYRateViewDelegate>)arg1 ;
-(NSObject*<DYRateViewDelegate>)delegate;
-(void)setAlignment:(int)arg1 ;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)setPadding:(float)arg1 ;
-(float)padding;
-(void)setEditable:(char)arg1 ;
-(int)alignment;
-(char)editable;
-(float)rate;
-(void)setRate:(float)arg1 ;
@end

