/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface Encrypt : NSObject
+(void)encryptScript:(id)arg1 with:(id)arg2 ;
+(id)decryptScript:(id)arg1 with:(id)arg2 ;
+(void)encryptWithSemaphore:(id)arg1 with:(id)arg2 ;
+(void)decryptWithSemaphore:(id)arg1 with:(id)arg2 ;
@end

