/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol WebFileResourceDelegate;
#import <AutoTouch/AutoTouch-Structs.h>
@class NSDictionary, HTTPConnection;

@interface FileResource : NSObject {

	CFHTTPMessageRef request;
	NSDictionary* parameters;
	HTTPConnection* connection;
	id<WebFileResourceDelegate> delegate;

}

@property (assign,nonatomic) id<WebFileResourceDelegate> delegate; 
+(char)canHandle:(CFHTTPMessageRef)arg1 ;
-(void)actionList;
-(void)actionShow:(id)arg1 ;
-(void)actionDelete:(id)arg1 ;
-(void)actionNew;
-(void)handleRequest;
-(void)dealloc;
-(void)setDelegate:(id<WebFileResourceDelegate>)arg1 ;
-(id<WebFileResourceDelegate>)delegate;
-(id)initWithConnection:(id)arg1 ;
@end

