/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <AutoTouch/AutoTouch-Structs.h>
@class NSString, FMDatabase;

@interface FMDatabaseQueue : NSObject {

	NSString* _path;
	dispatch_queue_sRef _queue;
	FMDatabase* _db;
	int _openFlags;

}

@property (retain) NSString * path;              //@synthesize path=_path - In the implementation block
@property (readonly) int openFlags;              //@synthesize openFlags=_openFlags - In the implementation block
+(Class)databaseClass;
+(id)databaseQueueWithPath:(id)arg1 ;
+(id)databaseQueueWithPath:(id)arg1 flags:(int)arg2 ;
-(id)inSavePoint:(/*^block*/id)arg1 ;
-(id)initWithPath:(id)arg1 flags:(int)arg2 ;
-(void)beginTransaction:(char)arg1 withBlock:(/*^block*/id)arg2 ;
-(void)inDatabase:(/*^block*/id)arg1 ;
-(void)inDeferredTransaction:(/*^block*/id)arg1 ;
-(void)inTransaction:(/*^block*/id)arg1 ;
-(int)openFlags;
-(id)database;
-(void)dealloc;
-(id)init;
-(NSString *)path;
-(void)setPath:(NSString *)arg1 ;
-(void)close;
-(id)initWithPath:(id)arg1 ;
@end

