/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <AutoTouch/AutoTouch-Structs.h>
@class NSString, NSMutableArray;

@interface FMDatabasePool : NSObject {

	NSString* _path;
	dispatch_queue_sRef _lockQueue;
	NSMutableArray* _databaseInPool;
	NSMutableArray* _databaseOutPool;
	id _delegate;
	unsigned _maximumNumberOfDatabasesToCreate;
	int _openFlags;

}

@property (retain) NSString * path;                                        //@synthesize path=_path - In the implementation block
@property (assign) id delegate;                                            //@synthesize delegate=_delegate - In the implementation block
@property (assign) unsigned maximumNumberOfDatabasesToCreate;              //@synthesize maximumNumberOfDatabasesToCreate=_maximumNumberOfDatabasesToCreate - In the implementation block
@property (readonly) int openFlags;                                        //@synthesize openFlags=_openFlags - In the implementation block
+(id)databasePoolWithPath:(id)arg1 ;
+(id)databasePoolWithPath:(id)arg1 flags:(int)arg2 ;
-(id)inSavePoint:(/*^block*/id)arg1 ;
-(id)initWithPath:(id)arg1 flags:(int)arg2 ;
-(void)executeLocked:(/*^block*/id)arg1 ;
-(void)pushDatabaseBackInPool:(id)arg1 ;
-(void)beginTransaction:(char)arg1 withBlock:(/*^block*/id)arg2 ;
-(unsigned)countOfCheckedInDatabases;
-(unsigned)countOfCheckedOutDatabases;
-(unsigned)countOfOpenDatabases;
-(void)releaseAllDatabases;
-(void)inDatabase:(/*^block*/id)arg1 ;
-(void)inDeferredTransaction:(/*^block*/id)arg1 ;
-(void)inTransaction:(/*^block*/id)arg1 ;
-(unsigned)maximumNumberOfDatabasesToCreate;
-(void)setMaximumNumberOfDatabasesToCreate:(unsigned)arg1 ;
-(int)openFlags;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)init;
-(id)delegate;
-(NSString *)path;
-(void)setPath:(NSString *)arg1 ;
-(id)initWithPath:(id)arg1 ;
-(id)db;
@end

