/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class FMDatabase, FMStatement, NSString, NSMutableDictionary;

@interface FMResultSet : NSObject {

	FMDatabase* _parentDB;
	FMStatement* _statement;
	NSString* _query;
	NSMutableDictionary* _columnNameToIndexMap;

}

@property (retain) NSString * query;                                          //@synthesize query=_query - In the implementation block
@property (readonly) NSMutableDictionary * columnNameToIndexMap; 
@property (retain) FMStatement * statement;                                   //@synthesize statement=_statement - In the implementation block
+(id)resultSetWithStatement:(id)arg1 usingParentDatabase:(id)arg2 ;
-(id)stringForColumn:(id)arg1 ;
-(char)boolForColumn:(id)arg1 ;
-(int)intForColumn:(id)arg1 ;
-(double)doubleForColumn:(id)arg1 ;
-(void)setParentDB:(id)arg1 ;
-(FMStatement *)statement;
-(void)setStatement:(FMStatement *)arg1 ;
-(NSMutableDictionary *)columnNameToIndexMap;
-(id)objectForColumnName:(id)arg1 ;
-(id)objectForColumnIndex:(int)arg1 ;
-(int)columnIndexForName:(id)arg1 ;
-(long)longForColumnIndex:(int)arg1 ;
-(long long)longLongIntForColumnIndex:(int)arg1 ;
-(unsigned long long)unsignedLongLongIntForColumnIndex:(int)arg1 ;
-(char)boolForColumnIndex:(int)arg1 ;
-(id)dateForColumnIndex:(int)arg1 ;
-(id)dataNoCopyForColumnIndex:(int)arg1 ;
-(char)columnIndexIsNull:(int)arg1 ;
-(const char*)UTF8StringForColumnIndex:(int)arg1 ;
-(void)kvcMagic:(id)arg1 ;
-(id)resultDict;
-(id)resultDictionary;
-(char)hasAnotherRow;
-(long)longForColumn:(id)arg1 ;
-(long long)longLongIntForColumn:(id)arg1 ;
-(unsigned long long)unsignedLongLongIntForColumn:(id)arg1 ;
-(id)dateForColumn:(id)arg1 ;
-(id)dataForColumn:(id)arg1 ;
-(id)dataNoCopyForColumn:(id)arg1 ;
-(char)columnIsNull:(id)arg1 ;
-(const char*)UTF8StringForColumnName:(id)arg1 ;
-(id)columnNameForIndex:(int)arg1 ;
-(void)setQuery:(NSString *)arg1 ;
-(void)dealloc;
-(id)objectAtIndexedSubscript:(int)arg1 ;
-(id)objectForKeyedSubscript:(id)arg1 ;
-(NSString *)query;
-(void)close;
-(int)columnCount;
-(id)stringForColumnIndex:(int)arg1 ;
-(int)intForColumnIndex:(int)arg1 ;
-(id)dataForColumnIndex:(int)arg1 ;
-(double)doubleForColumnIndex:(int)arg1 ;
-(char)next;
-(void)finalize;
@end

