/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <AutoTouch/AutoTouch-Structs.h>
@class NSString;

@interface FMStatement : NSObject {

	sqlite3_stmtRef _statement;
	NSString* _query;
	long _useCount;
	char _inUse;

}

@property (assign) long useCount;                          //@synthesize useCount=_useCount - In the implementation block
@property (retain) NSString * query;                       //@synthesize query=_query - In the implementation block
@property (assign) sqlite3_stmtRef statement;              //@synthesize statement=_statement - In the implementation block
@property (assign) char inUse;                             //@synthesize inUse=_inUse - In the implementation block
-(sqlite3_stmtRef)statement;
-(void)setStatement:(sqlite3_stmtRef)arg1 ;
-(void)setQuery:(NSString *)arg1 ;
-(void)dealloc;
-(id)description;
-(NSString *)query;
-(void)close;
-(void)reset;
-(long)useCount;
-(void)setUseCount:(long)arg1 ;
-(void)setInUse:(char)arg1 ;
-(char)inUse;
-(void)finalize;
@end

