/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <AutoTouch/AutoTouch-Structs.h>
@class NSString;

@interface HTTPAuthenticationRequest : NSObject {

	char isBasic;
	char isDigest;
	NSString* base64Credentials;
	NSString* username;
	NSString* realm;
	NSString* nonce;
	NSString* uri;
	NSString* qop;
	NSString* nc;
	NSString* cnonce;
	NSString* response;

}
-(id)quotedSubHeaderFieldValue:(id)arg1 fromHeaderFieldValue:(id)arg2 ;
-(id)nonquotedSubHeaderFieldValue:(id)arg1 fromHeaderFieldValue:(id)arg2 ;
-(char)isBasic;
-(char)isDigest;
-(id)base64Credentials;
-(id)qop;
-(id)nc;
-(id)cnonce;
-(id)realm;
-(void)dealloc;
-(id)initWithRequest:(CFHTTPMessageRef)arg1 ;
-(id)response;
-(id)nonce;
-(id)uri;
-(id)username;
@end

