/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/HTTPResponse.h>

@class NSData;

@interface HTTPDataResponse : NSObject <HTTPResponse> {

	unsigned offset;
	NSData* data;

}
-(unsigned long long)contentLength;
-(void)dealloc;
-(id)initWithData:(id)arg1 ;
-(void)setOffset:(unsigned long long)arg1 ;
-(unsigned long long)offset;
-(id)readDataOfLength:(unsigned)arg1 ;
@end

