/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol WebFileResourceDelegate;
@class AsyncSocket, NSString, NSNetService, NSDictionary, NSMutableArray;

@interface HTTPServer : NSObject {

	AsyncSocket* asyncSocket;
	id delegate;
	id<WebFileResourceDelegate> fileResourceDelegate;
	NSString* documentRoot;
	Class connectionClass;
	NSNetService* netService;
	NSString* domain;
	NSString* type;
	NSString* name;
	unsigned short port;
	NSDictionary* txtRecordDictionary;
	NSMutableArray* connections;

}

@property (assign,nonatomic) id<WebFileResourceDelegate> fileResourceDelegate; 
-(void)setupBuiltInDocroot;
-(void)setFileResourceDelegate:(id<WebFileResourceDelegate>)arg1 ;
-(void)connectionDidDie:(id)arg1 ;
-(void)setConnectionClass:(Class)arg1 ;
-(id)TXTRecordDictionary;
-(void)setTXTRecordDictionary:(id)arg1 ;
-(int)numberOfHTTPConnections;
-(void)onSocket:(id)arg1 didAcceptNewSocket:(id)arg2 ;
-(id<WebFileResourceDelegate>)fileResourceDelegate;
-(void)setPort:(unsigned short)arg1 ;
-(id)hostName;
-(void)netService:(id)arg1 didNotPublish:(id)arg2 ;
-(void)netServiceDidPublish:(id)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)init;
-(id)delegate;
-(void)setType:(id)arg1 ;
-(id)type;
-(id)domain;
-(void)setName:(id)arg1 ;
-(id)name;
-(char)stop;
-(char)start:(id*)arg1 ;
-(Class)connectionClass;
-(void)setDomain:(id)arg1 ;
-(id)documentRoot;
-(void)setDocumentRoot:(id)arg1 ;
-(unsigned short)port;
@end

