/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/IASKSettingsStore.h>

@interface IASKAbstractSettingsStore : NSObject <IASKSettingsStore>
-(double)doubleForKey:(id)arg1 ;
-(void)setInteger:(int)arg1 forKey:(id)arg2 ;
-(void)setFloat:(float)arg1 forKey:(id)arg2 ;
-(void)setDouble:(double)arg1 forKey:(id)arg2 ;
-(char)boolForKey:(id)arg1 ;
-(id)objectForKey:(id)arg1 ;
-(float)floatForKey:(id)arg1 ;
-(char)synchronize;
-(void)setObject:(id)arg1 forKey:(id)arg2 ;
-(void)setBool:(char)arg1 forKey:(id)arg2 ;
-(int)integerForKey:(id)arg1 ;
@end

