/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSDictionary, IASKSettingsReader;

@interface IASKSpecifier : NSObject {

	NSDictionary* _specifierDict;
	IASKSettingsReader* _settingsReader;
	NSDictionary* _multipleValuesDict;

}

@property (nonatomic,retain) NSDictionary * specifierDict;                            //@synthesize specifierDict=_specifierDict - In the implementation block
@property (assign,nonatomic,__weak) IASKSettingsReader * settingsReader;              //@synthesize settingsReader=_settingsReader - In the implementation block
@property (nonatomic,retain) NSDictionary * multipleValuesDict;                       //@synthesize multipleValuesDict=_multipleValuesDict - In the implementation block
-(void)setSpecifierDict:(NSDictionary *)arg1 ;
-(NSDictionary *)specifierDict;
-(void)_reinterpretValues:(id)arg1 ;
-(void)setMultipleValuesDict:(NSDictionary *)arg1 ;
-(id)localizedObjectForKey:(id)arg1 ;
-(id)multipleShortTitles;
-(id)trueValue;
-(id)falseValue;
-(id)cellImage;
-(Class)viewControllerClass;
-(SEL)viewControllerSelector;
-(id)viewControllerStoryBoardFile;
-(id)viewControllerStoryBoardID;
-(id)titleForCurrentValue:(id)arg1 ;
-(id)defaultStringValue;
-(char)defaultBoolValue;
-(int)autoCorrectionType;
-(id)highlightedCellImage;
-(NSDictionary *)multipleValuesDict;
-(id)multipleValues;
-(int)multipleValuesCount;
-(id)multipleTitles;
-(IASKSettingsReader *)settingsReader;
-(void)setSettingsReader:(IASKSettingsReader *)arg1 ;
-(id)initWithSpecifier:(id)arg1 ;
-(Class)buttonClass;
-(id)valueForKey:(id)arg1 ;
-(id)type;
-(id)title;
-(char)adjustsFontSizeToFitWidth;
-(int)textAlignment;
-(int)autocapitalizationType;
-(int)keyboardType;
-(id)minimumValueImage;
-(id)maximumValueImage;
-(float)minimumValue;
-(float)maximumValue;
-(id)key;
-(char)isSecure;
-(SEL)buttonAction;
-(id)footerText;
-(id)file;
-(id)defaultValue;
@end

