/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <UIKit/UIViewController.h>
#import <AutoTouch/IASKViewController.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>

@protocol IASKSettingsStore;
@class UITableView, IASKSpecifier, NSIndexPath, IASKSettingsReader;

@interface IASKSpecifierValuesViewController : UIViewController <IASKViewController, UITableViewDelegate, UITableViewDataSource> {

	UITableView* _tableView;
	IASKSpecifier* _currentSpecifier;
	NSIndexPath* _checkedItem;
	IASKSettingsReader* _settingsReader;
	id<IASKSettingsStore> _settingsStore;

}

@property (nonatomic,retain) UITableView * tableView;                          //@synthesize tableView=_tableView - In the implementation block
@property (nonatomic,retain) NSIndexPath * checkedItem;                        //@synthesize checkedItem=_checkedItem - In the implementation block
@property (nonatomic,retain) IASKSpecifier * currentSpecifier;                 //@synthesize currentSpecifier=_currentSpecifier - In the implementation block
@property (nonatomic,retain) IASKSettingsReader * settingsReader;              //@synthesize settingsReader=_settingsReader - In the implementation block
@property (nonatomic,retain) id<IASKSettingsStore> settingsStore;              //@synthesize settingsStore=_settingsStore - In the implementation block
-(id<IASKSettingsStore>)settingsStore;
-(void)setCheckedItem:(NSIndexPath *)arg1 ;
-(void)updateCheckedItem;
-(NSIndexPath *)checkedItem;
-(void)userDefaultsDidChange;
-(void)selectCell:(id)arg1 ;
-(void)deselectCell:(id)arg1 ;
-(IASKSettingsReader *)settingsReader;
-(void)setSettingsReader:(IASKSettingsReader *)arg1 ;
-(void)setSettingsStore:(id<IASKSettingsStore>)arg1 ;
-(void)setCurrentSpecifier:(IASKSpecifier *)arg1 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2 ;
-(void)didReceiveMemoryWarning;
-(void)setTableView:(UITableView *)arg1 ;
-(void)loadView;
-(char)shouldAutorotateToInterfaceOrientation:(int)arg1 ;
-(void)viewWillAppear:(char)arg1 ;
-(CGSize)contentSizeForViewInPopover;
-(void)viewDidUnload;
-(void)viewDidAppear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(UITableView *)tableView;
-(IASKSpecifier *)currentSpecifier;
@end

