/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

@class IASKSettingsReader;


@protocol IASKViewController <NSObject>
@property (nonatomic,retain) IASKSettingsReader * settingsReader; 
@property (nonatomic,retain) id<IASKSettingsStore> settingsStore; 
@required
-(id<IASKSettingsStore>)settingsStore;
-(IASKSettingsReader *)settingsReader;
-(void)setSettingsReader:(id)arg1;
-(void)setSettingsStore:(id)arg1;

@end

