/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class IASKTextField;

@interface IASKPSTextFieldSpecifierViewCell : UITableViewCell {

	IASKTextField* _textField;

}

@property (nonatomic,retain) IASKTextField * textField;              //@synthesize textField=_textField - In the implementation block
-(void)setTextField:(IASKTextField *)arg1 ;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(IASKTextField *)textField;
@end

