/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class IASKSlider, UIImageView;

@interface IASKPSSliderSpecifierViewCell : UITableViewCell {

	IASKSlider* _slider;
	UIImageView* _minImage;
	UIImageView* _maxImage;

}

@property (nonatomic,retain) IASKSlider * slider;                 //@synthesize slider=_slider - In the implementation block
@property (nonatomic,retain) UIImageView * minImage;              //@synthesize minImage=_minImage - In the implementation block
@property (nonatomic,retain) UIImageView * maxImage;              //@synthesize maxImage=_maxImage - In the implementation block
-(UIImageView *)minImage;
-(void)setMinImage:(UIImageView *)arg1 ;
-(UIImageView *)maxImage;
-(void)setMaxImage:(UIImageView *)arg1 ;
-(void)setSlider:(IASKSlider *)arg1 ;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(void)prepareForReuse;
-(IASKSlider *)slider;
@end

