/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSBundle, NSDictionary, NSString, NSArray, NSSet;

@interface IASKSettingsReader : NSObject {

	NSBundle* _applicationBundle;
	NSBundle* _settingsBundle;
	NSDictionary* _settingsDictionary;
	NSString* _localizationTable;
	NSArray* _dataSource;
	NSSet* _hiddenKeys;

}

@property (nonatomic,readonly) NSBundle * applicationBundle;                   //@synthesize applicationBundle=_applicationBundle - In the implementation block
@property (nonatomic,readonly) NSBundle * settingsBundle;                      //@synthesize settingsBundle=_settingsBundle - In the implementation block
@property (nonatomic,readonly) NSDictionary * settingsDictionary;              //@synthesize settingsDictionary=_settingsDictionary - In the implementation block
@property (nonatomic,retain) NSString * localizationTable;                     //@synthesize localizationTable=_localizationTable - In the implementation block
@property (nonatomic,retain) NSArray * dataSource;                             //@synthesize dataSource=_dataSource - In the implementation block
@property (nonatomic,retain) NSSet * hiddenKeys;                               //@synthesize hiddenKeys=_hiddenKeys - In the implementation block
-(id)locateSettingsFile:(id)arg1 ;
-(void)setLocalizationTable:(NSString *)arg1 ;
-(NSString *)localizationTable;
-(id)platformSuffixForInterfaceIdiom:(int)arg1 ;
-(NSBundle *)settingsBundle;
-(NSDictionary *)settingsDictionary;
-(void)_reinterpretBundle:(id)arg1 ;
-(id)initWithSettingsFileNamed:(id)arg1 applicationBundle:(id)arg2 ;
-(id)initWithFile:(id)arg1 ;
-(NSSet *)hiddenKeys;
-(char)_sectionHasHeading:(int)arg1 ;
-(NSBundle *)applicationBundle;
-(id)file:(id)arg1 withBundle:(id)arg2 suffix:(id)arg3 extension:(id)arg4 ;
-(void)setHiddenKeys:(NSSet *)arg1 ;
-(int)numberOfRowsForSection:(int)arg1 ;
-(id)specifierForIndexPath:(id)arg1 ;
-(id)indexPathForKey:(id)arg1 ;
-(id)keyForSection:(int)arg1 ;
-(id)footerTextForSection:(int)arg1 ;
-(id)pathForImageNamed:(id)arg1 ;
-(id)titleForStringId:(id)arg1 ;
-(id)titleForSection:(int)arg1 ;
-(void)setDataSource:(NSArray *)arg1 ;
-(id)init;
-(NSArray *)dataSource;
-(int)numberOfSections;
-(id)specifierForKey:(id)arg1 ;
@end

