/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:27 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <UIKit/UITableViewController.h>
#import <AutoTouch/IASKViewController.h>
#import <UIKit/UITextFieldDelegate.h>
#import <AutoTouch/MFMailComposeViewControllerDelegate.h>

@protocol IASKSettingsStore;
@class IASKSettingsReader, UIViewController, NSString, NSSet;

@interface IASKAppSettingsViewController : UITableViewController <IASKViewController, UITextFieldDelegate, MFMailComposeViewControllerDelegate> {

	IASKSettingsReader* _settingsReader;
	id<IASKSettingsStore> _settingsStore;
	id _currentFirstResponder;
	UIViewController* _currentChildViewController;
	char _reloadDisabled;
	char _showCreditsFooter;
	char _showDoneButton;
	NSString* _file;
	id _delegate;
	NSSet* _hiddenKeys;

}

@property (assign,nonatomic) id delegate;                                      //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) NSString * file;                                    //@synthesize file=_file - In the implementation block
@property (assign,nonatomic) char showCreditsFooter;                           //@synthesize showCreditsFooter=_showCreditsFooter - In the implementation block
@property (assign,nonatomic) char showDoneButton;                              //@synthesize showDoneButton=_showDoneButton - In the implementation block
@property (nonatomic,retain) NSSet * hiddenKeys;                               //@synthesize hiddenKeys=_hiddenKeys - In the implementation block
@property (nonatomic,retain) id currentFirstResponder;                         //@synthesize currentFirstResponder=_currentFirstResponder - In the implementation block
@property (nonatomic,retain) IASKSettingsReader * settingsReader;              //@synthesize settingsReader=_settingsReader - In the implementation block
@property (nonatomic,retain) id<IASKSettingsStore> settingsStore;              //@synthesize settingsStore=_settingsStore - In the implementation block
-(void)setShowDoneButton:(char)arg1 ;
-(void)setShowCreditsFooter:(char)arg1 ;
-(void)singleTapToEndEdit:(id)arg1 ;
-(void)synchronizeSettings;
-(void)setHiddenKeys:(id)arg1 animated:(char)arg2 ;
-(void)toggledValue:(id)arg1 ;
-(id)newCellForIdentifier:(id)arg1 ;
-(void)sliderChangedValue:(id)arg1 ;
-(char)showCreditsFooter;
-(char)showDoneButton;
-(NSSet *)hiddenKeys;
-(void)setHiddenKeys:(NSSet *)arg1 ;
-(id<IASKSettingsStore>)settingsStore;
-(void)userDefaultsDidChange;
-(IASKSettingsReader *)settingsReader;
-(void)setSettingsReader:(IASKSettingsReader *)arg1 ;
-(void)setSettingsStore:(id<IASKSettingsStore>)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)init;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2 ;
-(id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2 ;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2 ;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2 ;
-(void)reload;
-(id)delegate;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(char)textFieldShouldBeginEditing:(id)arg1 ;
-(char)textFieldShouldReturn:(id)arg1 ;
-(id)initWithStyle:(int)arg1 ;
-(char)shouldAutorotateToInterfaceOrientation:(int)arg1 ;
-(void)viewWillAppear:(char)arg1 ;
-(CGSize)contentSizeForViewInPopover;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewDidAppear:(char)arg1 ;
-(void)viewWillDisappear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3 ;
-(void)setFile:(NSString *)arg1 ;
-(NSString *)file;
-(void)_textChanged:(id)arg1 ;
-(char)isPad;
-(void)dismiss:(id)arg1 ;
-(void)setCurrentFirstResponder:(id)arg1 ;
-(id)currentFirstResponder;
@end

