/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <CoreFoundation/NSMutableArray.h>
#import <CoreFoundation/NSCopying.h>
#import <CoreFoundation/NSMutableCopying.h>
#import <CoreFoundation/NSFastEnumeration.h>

@interface JKArray : NSMutableArray <NSCopying, NSMutableCopying, NSFastEnumeration> {

	id* objects;
	unsigned count;
	unsigned capacity;
	unsigned mutations;

}
+(id)allocWithZone:(NSZone*)arg1 ;
-(void)dealloc;
-(unsigned)countByEnumeratingWithState:(SCD_Struct_JK18*)arg1 objects:(id*)arg2 count:(unsigned)arg3 ;
-(unsigned)count;
-(id)objectAtIndex:(unsigned)arg1 ;
-(void)insertObject:(id)arg1 atIndex:(unsigned)arg2 ;
-(void)removeObjectAtIndex:(unsigned)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)getObjects:(id*)arg1 range:(NSRange)arg2 ;
-(void)replaceObjectAtIndex:(unsigned)arg1 withObject:(id)arg2 ;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
@end

