/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <AutoTouch/AutoTouch-Structs.h>
@interface JKSerializer : NSObject {

	JKEncodeState* encodeState;

}
+(id)serializeObject:(id)arg1 options:(unsigned)arg2 encodeOption:(unsigned)arg3 block:(/*^block*/id)arg4 delegate:(id)arg5 selector:(SEL)arg6 error:(id*)arg7 ;
-(id)serializeObject:(id)arg1 options:(unsigned)arg2 encodeOption:(unsigned)arg3 block:(/*^block*/id)arg4 delegate:(id)arg5 selector:(SEL)arg6 error:(id*)arg7 ;
-(void)releaseState;
-(void)dealloc;
@end

