/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <AutoTouch/AutoTouch-Structs.h>
@interface JSONDecoder : NSObject {

	JKParseState* parseState;

}
+(id)decoderWithParseOptions:(unsigned)arg1 ;
+(id)decoder;
-(id)initWithParseOptions:(unsigned)arg1 ;
-(id)objectWithUTF8String:(const char*)arg1 length:(unsigned)arg2 error:(id*)arg3 ;
-(id)objectWithData:(id)arg1 error:(id*)arg2 ;
-(id)mutableObjectWithUTF8String:(const char*)arg1 length:(unsigned)arg2 error:(id*)arg3 ;
-(id)mutableObjectWithData:(id)arg1 error:(id*)arg2 ;
-(id)parseUTF8String:(const char*)arg1 length:(unsigned long)arg2 ;
-(id)parseUTF8String:(const char*)arg1 length:(unsigned long)arg2 error:(id*)arg3 ;
-(id)parseJSONData:(id)arg1 ;
-(id)parseJSONData:(id)arg1 error:(id*)arg2 ;
-(id)objectWithUTF8String:(const char*)arg1 length:(unsigned)arg2 ;
-(id)objectWithData:(id)arg1 ;
-(id)mutableObjectWithUTF8String:(const char*)arg1 length:(unsigned)arg2 ;
-(id)mutableObjectWithData:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)clearCache;
@end

