/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class MBProgressHUD;

@interface LicenseViewController : UIViewController {

	MBProgressHUD* _hud;

}
-(void)paypalPay;
-(void)alipayPay;
-(id)init;
-(void)didReceiveMemoryWarning;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(char)arg1 ;
@end

