/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <UIKit/UIViewController.h>
#import <UIKit/UITextViewDelegate.h>

@class UITextView;

@interface LogViewController : UIViewController <UITextViewDelegate> {

	UITextView* textView;

}
-(id)readLog;
-(void)clearLog;
-(void)didReceiveMemoryWarning;
-(void)viewDidLoad;
-(void)scrollRangeToVisible:(NSRange)arg1 ;
-(void)done;
-(void)clear;
@end

