/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <UIKit/UIView.h>

@protocol MBProgressHUDDelegate;
@class UILabel, UIColor, UIFont, UIView, NSTimer, NSDate, NSString;

@interface MBProgressHUD : UIView {

	char useAnimation;
	SEL methodForExecution;
	id targetForExecution;
	id objectForExecution;
	UILabel* label;
	UILabel* detailsLabel;
	char isFinished;
	CGAffineTransform rotationTransform;
	char square;
	char dimBackground;
	char taskInProgress;
	char removeFromSuperViewOnHide;
	int animationType;
	id<MBProgressHUDDelegate> delegate;
	float opacity;
	UIColor* color;
	UIFont* labelFont;
	UIFont* detailsLabelFont;
	UIView* indicator;
	float xOffset;
	float yOffset;
	float margin;
	float graceTime;
	float minShowTime;
	NSTimer* graceTimer;
	NSTimer* minShowTimer;
	UIView* customView;
	NSDate* showStarted;
	int mode;
	NSString* labelText;
	NSString* detailsLabelText;
	float progress;
	/*^block*/id completionBlock;
	CGSize minSize;
	CGSize size;

}

@property (copy) id completionBlock; 
@property (assign) int mode; 
@property (assign) int animationType; 
@property (retain) UIView * customView; 
@property (__weak) id<MBProgressHUDDelegate> delegate; 
@property (copy) NSString * labelText; 
@property (copy) NSString * detailsLabelText; 
@property (assign) float opacity; 
@property (retain) UIColor * color; 
@property (assign) float xOffset; 
@property (assign) float yOffset; 
@property (assign) float margin; 
@property (assign) char dimBackground; 
@property (assign) float graceTime; 
@property (assign) float minShowTime; 
@property (assign) char taskInProgress; 
@property (assign) char removeFromSuperViewOnHide; 
@property (retain) UIFont * labelFont; 
@property (retain) UIFont * detailsLabelFont; 
@property (assign) float progress; 
@property (assign) CGSize minSize; 
@property (getter=isSquare) char square; 
@property (retain) UIView * indicator; 
@property (retain) NSTimer * graceTimer; 
@property (retain) NSTimer * minShowTimer; 
@property (retain) NSDate * showStarted; 
@property (assign) CGSize size; 
+(id)showHUDAddedTo:(id)arg1 animated:(char)arg2 ;
+(id)HUDForView:(id)arg1 ;
+(id)allHUDsForView:(id)arg1 ;
+(char)hideHUDForView:(id)arg1 animated:(char)arg2 ;
+(unsigned)hideAllHUDsForView:(id)arg1 animated:(char)arg2 ;
-(void)hide:(char)arg1 afterDelay:(double)arg2 ;
-(void)setRemoveFromSuperViewOnHide:(char)arg1 ;
-(void)setDetailsLabelText:(NSString *)arg1 ;
-(void)setDetailsLabelFont:(UIFont *)arg1 ;
-(void)setXOffset:(float)arg1 ;
-(void)setDimBackground:(char)arg1 ;
-(void)setGraceTime:(float)arg1 ;
-(void)setMinShowTime:(float)arg1 ;
-(void)setupLabels;
-(void)updateIndicators;
-(void)registerForKVO;
-(void)unregisterFromNotifications;
-(void)unregisterFromKVO;
-(float)graceTime;
-(void)handleGraceTimer:(id)arg1 ;
-(void)setGraceTimer:(NSTimer *)arg1 ;
-(void)showUsingAnimation:(char)arg1 ;
-(float)minShowTime;
-(void)handleMinShowTimer:(id)arg1 ;
-(void)setMinShowTimer:(NSTimer *)arg1 ;
-(void)hideUsingAnimation:(char)arg1 ;
-(void)hideDelayed:(id)arg1 ;
-(void)setTransformForCurrentOrientation:(char)arg1 ;
-(void)setShowStarted:(NSDate *)arg1 ;
-(void)animationFinished:(id)arg1 finished:(char)arg2 context:(void*)arg3 ;
-(void)setTaskInProgress:(char)arg1 ;
-(void)launchExecution;
-(void)showAnimated:(char)arg1 whileExecutingBlock:(/*^block*/id)arg2 onQueue:(dispatch_queue_sRef)arg3 completionBlock:(/*^block*/id)arg4 ;
-(UIFont *)detailsLabelFont;
-(NSString *)detailsLabelText;
-(void)setIndicator:(UIView *)arg1 ;
-(char)dimBackground;
-(float)xOffset;
-(id)observableKeypaths;
-(void)updateUIForKeypath:(id)arg1 ;
-(void)showWhileExecuting:(SEL)arg1 onTarget:(id)arg2 withObject:(id)arg3 animated:(char)arg4 ;
-(void)showAnimated:(char)arg1 whileExecutingBlock:(/*^block*/id)arg2 ;
-(void)showAnimated:(char)arg1 whileExecutingBlock:(/*^block*/id)arg2 completionBlock:(/*^block*/id)arg3 ;
-(void)showAnimated:(char)arg1 whileExecutingBlock:(/*^block*/id)arg2 onQueue:(dispatch_queue_sRef)arg3 ;
-(UIView *)indicator;
-(NSTimer *)graceTimer;
-(NSTimer *)minShowTimer;
-(char)taskInProgress;
-(char)removeFromSuperViewOnHide;
-(NSDate *)showStarted;
-(void)setLabelFont:(UIFont *)arg1 ;
-(void)deviceOrientationDidChange:(id)arg1 ;
-(int)animationType;
-(NSString *)labelText;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(CGSize)size;
-(void)drawRect:(CGRect)arg1 ;
-(void)setDelegate:(id<MBProgressHUDDelegate>)arg1 ;
-(void)layoutSubviews;
-(id<MBProgressHUDDelegate>)delegate;
-(void)setSize:(CGSize)arg1 ;
-(void)didMoveToSuperview;
-(float)opacity;
-(void)setOpacity:(float)arg1 ;
-(void)setProgress:(float)arg1 ;
-(CGSize)minSize;
-(UIView *)customView;
-(void)setMode:(int)arg1 ;
-(int)mode;
-(id)initWithView:(id)arg1 ;
-(UIColor *)color;
-(void)setColor:(UIColor *)arg1 ;
-(void)done;
-(id)initWithWindow:(id)arg1 ;
-(void)show:(char)arg1 ;
-(void)cleanUp;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)setCustomView:(UIView *)arg1 ;
-(float)progress;
-(void)setCompletionBlock:(id)arg1 ;
-(id)completionBlock;
-(float)yOffset;
-(void)setYOffset:(float)arg1 ;
-(void)setMinSize:(CGSize)arg1 ;
-(void)registerForNotifications;
-(void)setSquare:(char)arg1 ;
-(char)isSquare;
-(void)setLabelText:(NSString *)arg1 ;
-(void)setAnimationType:(int)arg1 ;
-(UIFont *)labelFont;
-(float)margin;
-(void)setMargin:(float)arg1 ;
-(void)hide:(char)arg1 ;
@end

