/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <UIKit/UIView.h>

@class UIColor;

@interface MBRoundProgressView : UIView {

	char _annular;
	float _progress;
	UIColor* _progressTintColor;
	UIColor* _backgroundTintColor;

}

@property (assign,nonatomic) float progress;                             //@synthesize progress=_progress - In the implementation block
@property (nonatomic,retain) UIColor * progressTintColor;                //@synthesize progressTintColor=_progressTintColor - In the implementation block
@property (nonatomic,retain) UIColor * backgroundTintColor;              //@synthesize backgroundTintColor=_backgroundTintColor - In the implementation block
@property (assign,getter=isAnnular,nonatomic) char annular;              //@synthesize annular=_annular - In the implementation block
-(void)registerForKVO;
-(void)unregisterFromKVO;
-(void)setAnnular:(char)arg1 ;
-(id)observableKeypaths;
-(UIColor *)backgroundTintColor;
-(void)setBackgroundTintColor:(UIColor *)arg1 ;
-(char)isAnnular;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)drawRect:(CGRect)arg1 ;
-(id)init;
-(void)setProgress:(float)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(UIColor *)progressTintColor;
-(void)setProgressTintColor:(UIColor *)arg1 ;
-(float)progress;
@end

