/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/MobClickSBJsonBase.h>
#import <AutoTouch/MobClickSBJsonWriter.h>

@interface MobClickSBJsonWriter : MobClickSBJsonBase <MobClickSBJsonWriter> {

	char sortKeys;
	char humanReadable;

}

@property (assign) char humanReadable; 
@property (assign) char sortKeys; 
+(void)initialize;
-(id)stringWithFragment:(id)arg1 ;
-(id)stringWithObject:(id)arg1 ;
-(char)humanReadable;
-(void)setHumanReadable:(char)arg1 ;
-(char)sortKeys;
-(void)setSortKeys:(char)arg1 ;
-(char)appendValue:(id)arg1 into:(id)arg2 ;
-(char)appendDictionary:(id)arg1 into:(id)arg2 ;
-(char)appendArray:(id)arg1 into:(id)arg2 ;
-(char)appendString:(id)arg1 into:(id)arg2 ;
-(id)indent;
@end

