/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MobClickDelegate;
#import <AutoTouch/AutoTouch-Structs.h>
@class NSOperationQueue, UMANJob, NSMutableArray, NSMutableDictionary, NSString, NSDictionary;

@interface MobClickInternal : NSObject {

	NSOperationQueue* _sendQueue;
	NSOperationQueue* _creatQueue;
	UMANJob* _job;
	NSMutableArray* _launches;
	NSMutableArray* _terminates;
	NSMutableArray* _events;
	NSMutableArray* _errors;
	NSMutableDictionary* _pageViewHash;
	NSMutableArray* _pageViewArray;
	NSMutableArray* _ekv;
	NSMutableDictionary* _ekvSession;
	NSMutableArray* _currentEkvArray;
	NSMutableDictionary* _ekvBeginTimes;
	NSMutableDictionary* _eventBeginTimes;
	double lastLaunchTime;
	NSString* _lastSessionId;
	id<MobClickDelegate> _delegate;
	int policy;
	delegateHas* _delegateHas;
	NSDictionary* _error_support_info;

}

@property (nonatomic,retain) NSOperationQueue * sendQueue;               //@synthesize sendQueue=_sendQueue - In the implementation block
@property (nonatomic,retain) NSOperationQueue * creatQueue;              //@synthesize creatQueue=_creatQueue - In the implementation block
@property (retain) UMANJob * job;                                        //@synthesize job=_job - In the implementation block
@property (retain) NSMutableArray * launches;                            //@synthesize launches=_launches - In the implementation block
@property (retain) NSMutableArray * terminates;                          //@synthesize terminates=_terminates - In the implementation block
@property (retain) NSMutableArray * events;                              //@synthesize events=_events - In the implementation block
@property (retain) NSMutableArray * errors;                              //@synthesize errors=_errors - In the implementation block
@property (retain) NSMutableDictionary * pageViewHash;                   //@synthesize pageViewHash=_pageViewHash - In the implementation block
@property (retain) NSMutableArray * pageViewArray;                       //@synthesize pageViewArray=_pageViewArray - In the implementation block
@property (retain) NSMutableDictionary * ekvSession;                     //@synthesize ekvSession=_ekvSession - In the implementation block
@property (retain) NSMutableArray * currentEkvArray;                     //@synthesize currentEkvArray=_currentEkvArray - In the implementation block
@property (retain) NSMutableArray * ekv;                                 //@synthesize ekv=_ekv - In the implementation block
@property (retain) NSMutableDictionary * ekvBeginTimes;                  //@synthesize ekvBeginTimes=_ekvBeginTimes - In the implementation block
@property (retain) NSMutableDictionary * eventBeginTimes;                //@synthesize eventBeginTimes=_eventBeginTimes - In the implementation block
@property (assign) double lastLaunchTime; 
@property (copy) NSString * lastSessionId;                               //@synthesize lastSessionId=_lastSessionId - In the implementation block
@property (assign,nonatomic) id<MobClickDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) int policy; 
@property (assign,nonatomic) delegateHas* delegateHas;                   //@synthesize delegateHas=_delegateHas - In the implementation block
@property (retain) NSDictionary * error_support_info;                    //@synthesize error_support_info=_error_support_info - In the implementation block
+(void)error:(id)arg1 ;
+(void)loadJobFromFileAndInstance;
+(void)saveJobAndClean:(char)arg1 ;
+(void)internalSaveJobToFileAndClean:(id)arg1 ;
+(void)updateErrorSupportInfo:(id)arg1 ;
-(void)markJobDone;
-(void)removeInstanceDataInJobData;
-(void)clearJobData;
-(void)beginPerformJob;
-(NSMutableDictionary *)pageViewHash;
-(NSMutableArray *)pageViewArray;
-(NSMutableArray *)launches;
-(NSMutableArray *)terminates;
-(NSMutableArray *)ekv;
-(NSMutableDictionary *)ekvSession;
-(NSMutableArray *)currentEkvArray;
-(NSMutableDictionary *)eventBeginTimes;
-(void)setLastLaunchTime:(double)arg1 ;
-(void)setLastSessionId:(NSString *)arg1 ;
-(double)lastLaunchTime;
-(NSOperationQueue *)creatQueue;
-(NSMutableDictionary *)ekvBeginTimes;
-(delegateHas*)delegateHas;
-(void)setPolicy:(int)arg1 ;
-(void)setSendQueue:(NSOperationQueue *)arg1 ;
-(void)setCreatQueue:(NSOperationQueue *)arg1 ;
-(NSDictionary *)error_support_info;
-(void)setError_support_info:(NSDictionary *)arg1 ;
-(void)clearInstanceData;
-(void)fillJobDataFromInstance;
-(void)fillJobData;
-(void)commitJob;
-(void)jobToFile;
-(void)clearInstanceAndJobData;
-(id)loadJobDataFromFile;
-(void)fillJobDataFromDictionary:(id)arg1 ;
-(id)toDictionary:(char)arg1 ;
-(void)setLaunches:(NSMutableArray *)arg1 ;
-(void)setTerminates:(NSMutableArray *)arg1 ;
-(void)setEkv:(NSMutableArray *)arg1 ;
-(void)setPageViewHash:(NSMutableDictionary *)arg1 ;
-(void)setPageViewArray:(NSMutableArray *)arg1 ;
-(NSString *)lastSessionId;
-(void)setDelegateHas:(delegateHas*)arg1 ;
-(void)setEkvSession:(NSMutableDictionary *)arg1 ;
-(void)setCurrentEkvArray:(NSMutableArray *)arg1 ;
-(void)setEkvBeginTimes:(NSMutableDictionary *)arg1 ;
-(void)setEventBeginTimes:(NSMutableDictionary *)arg1 ;
-(int)policy;
-(NSMutableArray *)events;
-(void)dealloc;
-(void)setDelegate:(id<MobClickDelegate>)arg1 ;
-(id)init;
-(id<MobClickDelegate>)delegate;
-(NSOperationQueue *)sendQueue;
-(UMANJob *)job;
-(void)setJob:(UMANJob *)arg1 ;
-(void)setEvents:(NSMutableArray *)arg1 ;
-(id)header;
-(NSMutableArray *)errors;
-(void)setErrors:(NSMutableArray *)arg1 ;
@end

