/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/MobClickSBJsonBase.h>
#import <AutoTouch/MobClickSBJsonParser.h>
#import <AutoTouch/MobClickSBJsonWriter.h>

@class MobClickSBJsonParser, MobClickSBJsonWriter;

@interface MobClickSBJSON : MobClickSBJsonBase <MobClickSBJsonParser, MobClickSBJsonWriter> {

	MobClickSBJsonParser* jsonParser;
	MobClickSBJsonWriter* jsonWriter;

}

@property (assign) char humanReadable; 
@property (assign) char sortKeys; 
-(id)stringWithObject:(id)arg1 ;
-(id)objectWithString:(id)arg1 ;
-(id)stringWithObject:(id)arg1 allowScalar:(char)arg2 error:(id*)arg3 ;
-(id)objectWithString:(id)arg1 allowScalar:(char)arg2 error:(id*)arg3 ;
-(char)humanReadable;
-(void)setHumanReadable:(char)arg1 ;
-(char)sortKeys;
-(void)setSortKeys:(char)arg1 ;
-(id)stringWithFragment:(id)arg1 error:(id*)arg2 ;
-(id)stringWithObject:(id)arg1 error:(id*)arg2 ;
-(id)fragmentWithString:(id)arg1 error:(id*)arg2 ;
-(id)objectWithString:(id)arg1 error:(id*)arg2 ;
-(void)dealloc;
-(id)init;
-(unsigned)maxDepth;
-(void)setMaxDepth:(unsigned)arg1 ;
@end

