/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/MobClickSBJsonBase.h>
#import <AutoTouch/MobClickSBJsonParser.h>

@interface MobClickSBJsonParser : MobClickSBJsonBase <MobClickSBJsonParser> {

	const char* c;

}
+(void)initialize;
-(id)objectWithString:(id)arg1 ;
-(char)scanValue:(id*)arg1 ;
-(char)scanIsAtEnd;
-(id)fragmentWithString:(id)arg1 ;
-(char)scanRestOfDictionary:(id*)arg1 ;
-(char)scanRestOfArray:(id*)arg1 ;
-(char)scanRestOfString:(id*)arg1 ;
-(char)scanRestOfFalse:(id*)arg1 ;
-(char)scanRestOfTrue:(id*)arg1 ;
-(char)scanRestOfNull:(id*)arg1 ;
-(char)scanNumber:(id*)arg1 ;
-(char)scanUnicodeChar:(unsigned short*)arg1 ;
-(char)scanHexQuad:(unsigned short*)arg1 ;
@end

