/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIAlertViewDelegate.h>

@class NSString;

@interface MobClick : NSObject <UIAlertViewDelegate> {

	id _internal;
	NSString* _wrapperVersion;
	NSString* _wrapperType;

}

@property (nonatomic,copy) NSString * wrapperType;                 //@synthesize wrapperType=_wrapperType - In the implementation block
@property (nonatomic,copy) NSString * wrapperVersion;              //@synthesize wrapperVersion=_wrapperVersion - In the implementation block
+(void)startWithAppkey:(id)arg1 ;
+(void)event:(id)arg1 ;
+(id)sharedInternal;
+(int)reportPolicy;
+(void)setUmengJobRunning:(char)arg1 ;
+(void)installUncaughtExceptionHandler;
+(void)saveCrashInfo:(id)arg1 ;
+(char)shouldCommitJob:(int)arg1 ;
+(void)preparePerformJob:(int)arg1 ;
+(void)markAppLaunchedTime;
+(char)validEventID:(id)arg1 ;
+(void)eventJob:(id)arg1 ;
+(void)eventJob:(id)arg1 label:(id)arg2 acc:(int)arg3 du:(int)arg4 ;
+(void)beginEvent:(id)arg1 label:(id)arg2 ;
+(void)endEvent:(id)arg1 label:(id)arg2 ;
+(void)event:(id)arg1 attributes:(id)arg2 durations:(int)arg3 ;
+(void)ekvPerformJob;
+(id)setAppUpdateData;
+(SEL)appUpdateSeletor;
+(void)appUpdateWithAlert:(id)arg1 ;
+(char)checkAppUpdate:(id)arg1 ;
+(void)checkAppUpdateResult;
+(void)checkUpdate:(id)arg1 cancelButtonTitle:(id)arg2 otherButtonTitles:(id)arg3 ;
+(void)setAppUpdateSeletor:(SEL)arg1 ;
+(void)checkUpdate;
+(id)setConfigData;
+(void)setReportPolicy:(int)arg1 ;
+(void)setLogSendInterval:(double)arg1 ;
+(char)getOnlineConfigParams:(id)arg1 ;
+(void)postOnlineConfigDidFinishedNotification;
+(id)getConfigParams;
+(void)_updateOnlineConfig;
+(void)logPageView:(id)arg1 seconds:(int)arg2 ;
+(void)launchJob;
+(void)markTerminatedTime;
+(void)setDelegate:(id)arg1 reportPolicy:(int)arg2 ;
+(void)addObserverForSession;
+(id)getAgentVersion;
+(void)ensureFirstLaunch;
+(void)startSession:(id)arg1 ;
+(void)startWithAppkey:(id)arg1 reportPolicy:(int)arg2 channelId:(id)arg3 ;
+(void)stopSession:(id)arg1 ;
+(void)setCrashReportEnabled:(char)arg1 ;
+(void)setWrapperType:(id)arg1 ;
+(void)setWrapperVersion:(id)arg1 ;
+(void)setLogEnabled:(char)arg1 ;
+(char)umengLogEnabled;
+(unsigned)umengJobPolicy;
+(char)hasUmengJobRunning;
+(void)setAppCrashed:(char)arg1 ;
+(void)logPageView:(id)arg1 ;
+(void)event:(id)arg1 label:(id)arg2 ;
+(void)event:(id)arg1 acc:(int)arg2 ;
+(void)event:(id)arg1 label:(id)arg2 acc:(int)arg3 ;
+(void)event:(id)arg1 durations:(int)arg2 ;
+(void)event:(id)arg1 label:(id)arg2 durations:(int)arg3 ;
+(void)event:(id)arg1 attributes:(id)arg2 ;
+(void)beginEvent:(id)arg1 primarykey:(id)arg2 attributes:(id)arg3 ;
+(void)endEvent:(id)arg1 primarykey:(id)arg2 ;
+(char)isJailbroken;
+(char)isPirated;
+(void)checkUpdateWithDelegate:(id)arg1 selector:(SEL)arg2 ;
+(void)updateOnlineConfig;
+(void)updateOnlineConfigSync;
+(void)beginLogPageView:(id)arg1 ;
+(void)endLogPageView:(id)arg1 ;
+(id)umengPageViews;
+(id)getConfigParams:(id)arg1 ;
+(void)appLaunched;
+(void)appTerminated;
+(void)setWrapperType:(id)arg1 wrapperVersion:(id)arg2 ;
+(void)beginEvent:(id)arg1 ;
+(void)endEvent:(id)arg1 ;
+(void)setDelegate:(id)arg1 ;
+(id)sharedInstance;
+(void)initialize;
+(id)sessionID;
+(id)appVersion;
+(void)setAppVersion:(id)arg1 ;
+(void)setLatitude:(double)arg1 longitude:(double)arg2 ;
+(void)setLocation:(id)arg1 ;
-(id)appKey;
-(id)channelId;
-(id)user_id;
-(void)setWrapperType:(NSString *)arg1 ;
-(void)setWrapperVersion:(NSString *)arg1 ;
-(void)noAppKeyException;
-(NSString *)wrapperVersion;
-(NSString *)wrapperType;
-(id)internal;
-(void)dealloc;
-(id)init;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(int)age;
-(int)gender;
@end

