/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSMutableArray, NSArray;

@interface MobClickSBJsonBase : NSObject {

	NSMutableArray* errorTrace;
	unsigned depth;
	unsigned maxDepth;

}

@property (assign) unsigned maxDepth; 
@property (readonly) NSArray * errorTrace; 
-(NSArray *)errorTrace;
-(void)clearErrorTrace;
-(void)addErrorWithCode:(unsigned)arg1 description:(id)arg2 ;
-(void)dealloc;
-(id)init;
-(unsigned)maxDepth;
-(void)setMaxDepth:(unsigned)arg1 ;
@end

