/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <UIKit/UIToolbar.h>

@protocol MWPhoto;
@class UILabel;

@interface MWCaptionView : UIToolbar {

	id<MWPhoto> _photo;
	UILabel* _label;

}
-(void)setupCaption;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id)initWithPhoto:(id)arg1 ;
@end

