/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <AutoTouch/PSTCollectionViewCell.h>

@protocol MWPhoto;
@class UIImageView, DACircularProgressView, UIButton, MWGridViewController;

@interface MWGridCell : PSTCollectionViewCell {

	UIImageView* _imageView;
	UIImageView* _loadingError;
	DACircularProgressView* _loadingIndicator;
	UIButton* _selectedButton;
	char _selectionMode;
	char _isSelected;
	MWGridViewController* _gridController;
	unsigned _index;
	id<MWPhoto> _photo;

}

@property (assign,nonatomic,__weak) MWGridViewController * gridController;              //@synthesize gridController=_gridController - In the implementation block
@property (assign,nonatomic) unsigned index;                                            //@synthesize index=_index - In the implementation block
@property (nonatomic,retain) id<MWPhoto> photo;                                         //@synthesize photo=_photo - In the implementation block
@property (assign,nonatomic) char selectionMode;                                        //@synthesize selectionMode=_selectionMode - In the implementation block
@property (assign,nonatomic) char isSelected;                                           //@synthesize isSelected=_isSelected - In the implementation block
-(void)selectionButtonPressed;
-(void)setProgressFromNotification:(id)arg1 ;
-(void)handleMWPhotoLoadingDidEndNotification:(id)arg1 ;
-(void)hideImageFailure;
-(void)showImageFailure;
-(void)setSelectionMode:(char)arg1 ;
-(MWGridViewController *)gridController;
-(void)setGridController:(MWGridViewController *)arg1 ;
-(char)selectionMode;
-(void)showLoadingIndicator;
-(void)hideLoadingIndicator;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(char)isSelected;
-(void)prepareForReuse;
-(unsigned)index;
-(void)displayImage;
-(void)setIndex:(unsigned)arg1 ;
-(void)setIsSelected:(char)arg1 ;
-(id<MWPhoto>)photo;
-(void)setPhoto:(id<MWPhoto>)arg1 ;
@end

