/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <AutoTouch/PSTCollectionViewController.h>

@class MWPhotoBrowser;

@interface MWGridViewController : PSTCollectionViewController {

	float _margin;
	float _gutter;
	float _marginL;
	float _gutterL;
	float _columns;
	float _columnsL;
	char _selectionMode;
	MWPhotoBrowser* _browser;
	CGPoint _initialContentOffset;

}

@property (assign,nonatomic) MWPhotoBrowser * browser;                  //@synthesize browser=_browser - In the implementation block
@property (assign,nonatomic) char selectionMode;                        //@synthesize selectionMode=_selectionMode - In the implementation block
@property (assign,nonatomic) CGPoint initialContentOffset;              //@synthesize initialContentOffset=_initialContentOffset - In the implementation block
-(void)setSelectionMode:(char)arg1 ;
-(char)selectionMode;
-(float)getGutter;
-(float)getMargin;
-(float)getColumns;
-(CGPoint)initialContentOffset;
-(void)setInitialContentOffset:(CGPoint)arg1 ;
-(MWPhotoBrowser *)browser;
-(void)setBrowser:(MWPhotoBrowser *)arg1 ;
-(id)init;
-(void)viewWillLayoutSubviews;
-(void)viewDidLayoutSubviews;
-(void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2 ;
-(void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3 ;
-(int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2 ;
-(id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2 ;
-(CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3 ;
-(void)viewDidLoad;
-(void)viewWillDisappear:(char)arg1 ;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2 ;
-(UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(int)arg3 ;
-(float)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(int)arg3 ;
-(float)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(int)arg3 ;
-(void)performLayout;
@end

