/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <UIKit/UIViewController.h>
#import <UIKit/UIScrollViewDelegate.h>
#import <UIKit/UIActionSheetDelegate.h>
#import <AutoTouch/MFMailComposeViewControllerDelegate.h>

@protocol MWPhotoBrowserDelegate;
@class NSMutableArray, NSArray, UIScrollView, NSMutableSet, UIToolbar, NSTimer, UIBarButtonItem, MBProgressHUD, UIActionSheet, MWGridViewController, UIColor, UIImage, UIActivityViewController;

@interface MWPhotoBrowser : UIViewController <UIScrollViewDelegate, UIActionSheetDelegate, MFMailComposeViewControllerDelegate> {

	unsigned _photoCount;
	NSMutableArray* _photos;
	NSMutableArray* _thumbPhotos;
	NSArray* _depreciatedPhotoData;
	UIScrollView* _pagingScrollView;
	NSMutableSet* _visiblePages;
	NSMutableSet* _recycledPages;
	unsigned _currentPageIndex;
	unsigned _previousPageIndex;
	CGRect _previousLayoutBounds;
	unsigned _pageIndexBeforeRotation;
	UIToolbar* _toolbar;
	NSTimer* _controlVisibilityTimer;
	UIBarButtonItem* _previousButton;
	UIBarButtonItem* _nextButton;
	UIBarButtonItem* _actionButton;
	UIBarButtonItem* _doneButton;
	MBProgressHUD* _progressHUD;
	UIActionSheet* _actionsSheet;
	MWGridViewController* _gridController;
	UIBarButtonItem* _gridPreviousLeftNavItem;
	UIBarButtonItem* _gridPreviousRightNavItem;
	char _previousNavBarHidden;
	char _previousNavToolbarHidden;
	char _previousNavBarTranslucent;
	int _previousNavBarStyle;
	int _previousStatusBarStyle;
	UIColor* _previousNavBarTintColor;
	UIColor* _previousNavBarBarTintColor;
	UIBarButtonItem* _previousViewControllerBackButton;
	UIImage* _previousNavigationBarBackgroundImageDefault;
	UIImage* _previousNavigationBarBackgroundImageLandscapePhone;
	char _hasBelongedToViewController;
	char _isVCBasedStatusBarAppearance;
	char _statusBarShouldBeHidden;
	char _displayActionButton;
	char _leaveStatusBarAlone;
	char _performingLayout;
	char _rotating;
	char _viewIsActive;
	char _didSavePreviousStateOfNavBar;
	char _skipNextPagingScrollViewPositioning;
	char _viewHasAppearedInitially;
	CGPoint _currentGridContentOffset;
	char _zoomPhotosToFill;
	char _displayNavArrows;
	char _displaySelectionButtons;
	char _alwaysShowControls;
	char _enableGrid;
	char _enableSwipeToDismiss;
	char _startOnGrid;
	id<MWPhotoBrowserDelegate> _delegate;
	unsigned _delayToHideElements;
	UIActivityViewController* _activityViewController;

}

@property (assign,nonatomic,__weak) id<MWPhotoBrowserDelegate> delegate;                     //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) char zoomPhotosToFill;                                          //@synthesize zoomPhotosToFill=_zoomPhotosToFill - In the implementation block
@property (assign,nonatomic) char displayNavArrows;                                          //@synthesize displayNavArrows=_displayNavArrows - In the implementation block
@property (assign,nonatomic) char displayActionButton;                                       //@synthesize displayActionButton=_displayActionButton - In the implementation block
@property (assign,nonatomic) char displaySelectionButtons;                                   //@synthesize displaySelectionButtons=_displaySelectionButtons - In the implementation block
@property (assign,nonatomic) char alwaysShowControls;                                        //@synthesize alwaysShowControls=_alwaysShowControls - In the implementation block
@property (assign,nonatomic) char enableGrid;                                                //@synthesize enableGrid=_enableGrid - In the implementation block
@property (assign,nonatomic) char enableSwipeToDismiss;                                      //@synthesize enableSwipeToDismiss=_enableSwipeToDismiss - In the implementation block
@property (assign,nonatomic) char startOnGrid;                                               //@synthesize startOnGrid=_startOnGrid - In the implementation block
@property (assign,nonatomic) unsigned delayToHideElements;                                   //@synthesize delayToHideElements=_delayToHideElements - In the implementation block
@property (nonatomic,readonly) unsigned currentIndex; 
@property (nonatomic,retain) UIActivityViewController * activityViewController;              //@synthesize activityViewController=_activityViewController - In the implementation block
-(void)setDisplayActionButton:(char)arg1 ;
-(void)setDisplayNavArrows:(char)arg1 ;
-(void)setDisplaySelectionButtons:(char)arg1 ;
-(void)setZoomPhotosToFill:(char)arg1 ;
-(void)setAlwaysShowControls:(char)arg1 ;
-(void)setEnableGrid:(char)arg1 ;
-(void)setStartOnGrid:(char)arg1 ;
-(void)showNextPhotoAnimated:(char)arg1 ;
-(void)showPreviousPhotoAnimated:(char)arg1 ;
-(void)setCurrentPhotoIndex:(unsigned)arg1 ;
-(void)handleMWPhotoLoadingDidEndNotification:(id)arg1 ;
-(void)setPhotoSelected:(char)arg1 atIndex:(unsigned)arg2 ;
-(id)thumbPhotoAtIndex:(unsigned)arg1 ;
-(char)photoIsSelectedAtIndex:(unsigned)arg1 ;
-(void)hideGrid;
-(void)_initialisation;
-(void)releaseAllUnderlyingPhotos:(char)arg1 ;
-(CGRect)frameForPagingScrollView;
-(CGSize)contentSizeForPagingScrollView;
-(CGRect)frameForToolbarAtOrientation:(int)arg1 ;
-(char)displayNavArrows;
-(void)gotoPreviousPage;
-(void)gotoNextPage;
-(char)displayActionButton;
-(void)doneButtonPressed:(id)arg1 ;
-(void)showGridAnimated;
-(void)updateNavigation;
-(CGPoint)contentOffsetForPageAtIndex:(unsigned)arg1 ;
-(void)tilePages;
-(char)presentingViewControllerPrefersStatusBarHidden;
-(void)storePreviousNavBarAppearance;
-(void)setNavBarAppearance:(char)arg1 ;
-(void)showGrid:(char)arg1 ;
-(void)restorePreviousNavBarAppearance:(char)arg1 ;
-(void)setControlsHidden:(char)arg1 animated:(char)arg2 permanent:(char)arg3 ;
-(void)layoutVisiblePages;
-(CGRect)frameForPageAtIndex:(unsigned)arg1 ;
-(CGRect)frameForCaptionView:(id)arg1 atIndex:(unsigned)arg2 ;
-(CGRect)frameForSelectedButton:(id)arg1 atIndex:(unsigned)arg2 ;
-(void)didStartViewingPageAtIndex:(unsigned)arg1 ;
-(char)areControlsHidden;
-(id)pageDisplayingPhoto:(id)arg1 ;
-(void)loadAdjacentPhotosIfNecessary:(id)arg1 ;
-(char)isDisplayingPageForIndex:(unsigned)arg1 ;
-(id)dequeueRecycledPage;
-(void)configurePage:(id)arg1 forIndex:(unsigned)arg2 ;
-(id)captionViewForPhotoAtIndex:(unsigned)arg1 ;
-(char)displaySelectionButtons;
-(void)selectedButtonTapped:(id)arg1 ;
-(void)jumpToPageAtIndex:(unsigned)arg1 animated:(char)arg2 ;
-(void)updateVisiblePageStates;
-(unsigned)delayToHideElements;
-(void)showProgressHUDWithMessage:(id)arg1 ;
-(void)hideProgressHUD:(char)arg1 ;
-(void)savePhoto;
-(void)copyPhoto;
-(void)emailPhoto;
-(id)progressHUD;
-(void)actuallySavePhoto:(id)arg1 ;
-(void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void*)arg3 ;
-(void)showProgressHUDCompleteMessage:(id)arg1 ;
-(void)actuallyCopyPhoto:(id)arg1 ;
-(void)actuallyEmailPhoto:(id)arg1 ;
-(id)initWithPhotos:(id)arg1 ;
-(id)pageDisplayedAtIndex:(unsigned)arg1 ;
-(void)setInitialPageIndex:(unsigned)arg1 ;
-(char)alwaysShowControls;
-(char)enableGrid;
-(char)enableSwipeToDismiss;
-(void)setEnableSwipeToDismiss:(char)arg1 ;
-(char)startOnGrid;
-(void)setDelayToHideElements:(unsigned)arg1 ;
-(id)imageForPhoto:(id)arg1 ;
-(char)zoomPhotosToFill;
-(void)cancelControlHiding;
-(void)hideControlsAfterDelay;
-(void)toggleControls;
-(void)dealloc;
-(id)initWithCoder:(id)arg1 ;
-(void)setDelegate:(id<MWPhotoBrowserDelegate>)arg1 ;
-(void)reloadData;
-(id)init;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewWillBeginDragging:(id)arg1 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(id<MWPhotoBrowserDelegate>)delegate;
-(char)prefersStatusBarHidden;
-(int)preferredStatusBarUpdateAnimation;
-(void)didReceiveMemoryWarning;
-(unsigned)supportedInterfaceOrientations;
-(void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2 ;
-(void)viewWillLayoutSubviews;
-(unsigned)currentIndex;
-(char)shouldAutorotateToInterfaceOrientation:(int)arg1 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)willMoveToParentViewController:(id)arg1 ;
-(void)didMoveToParentViewController:(id)arg1 ;
-(void)viewDidAppear:(char)arg1 ;
-(void)viewWillDisappear:(char)arg1 ;
-(void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2 ;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2 ;
-(void)didRotateFromInterfaceOrientation:(int)arg1 ;
-(void)hideControls;
-(UIActivityViewController *)activityViewController;
-(void)setActivityViewController:(UIActivityViewController *)arg1 ;
-(void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3 ;
-(void)actionButtonPressed:(id)arg1 ;
-(void)performLayout;
-(id)photoAtIndex:(unsigned)arg1 ;
-(unsigned)numberOfPhotos;
-(id)initWithDelegate:(id)arg1 ;
@end

