/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MWPhotoBrowserDelegate <NSObject>
@optional
-(id)photoBrowser:(id)arg1 thumbPhotoAtIndex:(unsigned)arg2;
-(id)photoBrowser:(id)arg1 captionViewForPhotoAtIndex:(unsigned)arg2;
-(id)photoBrowser:(id)arg1 titleForPhotoAtIndex:(unsigned)arg2;
-(void)photoBrowser:(id)arg1 didDisplayPhotoAtIndex:(unsigned)arg2;
-(void)photoBrowser:(id)arg1 actionButtonPressedForPhotoAtIndex:(unsigned)arg2;
-(char)photoBrowser:(id)arg1 isPhotoSelectedAtIndex:(unsigned)arg2;
-(void)photoBrowser:(id)arg1 photoAtIndex:(unsigned)arg2 selectedChanged:(char)arg3;
-(void)photoBrowserDidFinishModalPresentation:(id)arg1;

@required
-(unsigned)numberOfPhotosInPhotoBrowser:(id)arg1;
-(id)photoBrowser:(id)arg1 photoAtIndex:(unsigned)arg2;

@end

