/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/MWPhoto.h>
@class UIImage;


@protocol MWPhoto <NSObject>
@property (nonatomic,retain) UIImage * underlyingImage; 
@optional
-(void)cancelAnyLoading;
-(id)caption;

@required
-(UIImage *)underlyingImage;
-(void)performLoadUnderlyingImageAndNotify;
-(void)setUnderlyingImage:(id)arg1;
-(void)loadUnderlyingImageAndNotify;
-(void)unloadUnderlyingImage;

@end


@protocol SDWebImageOperation;
@class UIImage, NSString, NSURL;

@interface MWPhoto : NSObject <MWPhoto> {

	char _loadingInProgress;
	id<SDWebImageOperation> _webImageOperation;
	UIImage* _underlyingImage;
	NSString* _caption;
	UIImage* _image;
	NSURL* _photoURL;
	NSString* _filePath;

}

@property (nonatomic,retain) NSString * caption;                     //@synthesize caption=_caption - In the implementation block
@property (nonatomic,readonly) UIImage * image;                      //@synthesize image=_image - In the implementation block
@property (nonatomic,readonly) NSURL * photoURL;                     //@synthesize photoURL=_photoURL - In the implementation block
@property (nonatomic,readonly) NSString * filePath;                  //@synthesize filePath=_filePath - In the implementation block
@property (nonatomic,retain) UIImage * underlyingImage;              //@synthesize underlyingImage=_underlyingImage - In the implementation block
+(id)photoWithURL:(id)arg1 ;
+(id)photoWithImage:(id)arg1 ;
+(id)photoWithFilePath:(id)arg1 ;
-(UIImage *)underlyingImage;
-(void)imageLoadingComplete;
-(void)performLoadUnderlyingImageAndNotify;
-(void)setUnderlyingImage:(UIImage *)arg1 ;
-(void)postCompleteNotification;
-(void)loadUnderlyingImageAndNotify;
-(void)unloadUnderlyingImage;
-(void)cancelAnyLoading;
-(NSURL *)photoURL;
-(id)initWithImage:(id)arg1 ;
-(UIImage *)image;
-(id)initWithURL:(id)arg1 ;
-(NSString *)filePath;
-(id)initWithFilePath:(id)arg1 ;
-(NSString *)caption;
-(void)setCaption:(NSString *)arg1 ;
@end

