/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <UIKit/UIView.h>

@protocol MWTapDetectingViewDelegate;
@interface MWTapDetectingView : UIView {

	id<MWTapDetectingViewDelegate> _tapDelegate;

}

@property (assign,nonatomic,__weak) id<MWTapDetectingViewDelegate> tapDelegate;              //@synthesize tapDelegate=_tapDelegate - In the implementation block
-(void)handleSingleTap:(id)arg1 ;
-(void)handleTripleTap:(id)arg1 ;
-(void)handleDoubleTap:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)init;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)setTapDelegate:(id<MWTapDetectingViewDelegate>)arg1 ;
-(id<MWTapDetectingViewDelegate>)tapDelegate;
@end

