/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:28 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <UIKit/UIScrollView.h>
#import <UIKit/UIScrollViewDelegate.h>
#import <AutoTouch/MWTapDetectingImageViewDelegate.h>
#import <AutoTouch/MWTapDetectingViewDelegate.h>

@protocol MWPhoto;
@class MWPhotoBrowser, MWTapDetectingView, MWTapDetectingImageView, DACircularProgressView, UIImageView, MWCaptionView, UIButton;

@interface MWZoomingScrollView : UIScrollView <UIScrollViewDelegate, MWTapDetectingImageViewDelegate, MWTapDetectingViewDelegate> {

	MWPhotoBrowser* _photoBrowser;
	MWTapDetectingView* _tapView;
	MWTapDetectingImageView* _photoImageView;
	DACircularProgressView* _loadingIndicator;
	UIImageView* _loadingError;
	unsigned _index;
	id<MWPhoto> _photo;
	MWCaptionView* _captionView;
	UIButton* _selectedButton;

}

@property (assign) unsigned index;                                            //@synthesize index=_index - In the implementation block
@property (nonatomic,retain) id<MWPhoto> photo;                               //@synthesize photo=_photo - In the implementation block
@property (assign,nonatomic,__weak) MWCaptionView * captionView;              //@synthesize captionView=_captionView - In the implementation block
@property (assign,nonatomic,__weak) UIButton * selectedButton;                //@synthesize selectedButton=_selectedButton - In the implementation block
-(void)setProgressFromNotification:(id)arg1 ;
-(void)hideImageFailure;
-(void)handleSingleTap:(CGPoint)arg1 ;
-(void)imageView:(id)arg1 singleTapDetected:(id)arg2 ;
-(void)imageView:(id)arg1 doubleTapDetected:(id)arg2 ;
-(void)setCaptionView:(MWCaptionView *)arg1 ;
-(void)displayImageFailure;
-(float)initialZoomScaleWithMinScale;
-(void)view:(id)arg1 singleTapDetected:(id)arg2 ;
-(void)view:(id)arg1 doubleTapDetected:(id)arg2 ;
-(id)initWithPhotoBrowser:(id)arg1 ;
-(MWCaptionView *)captionView;
-(void)handleDoubleTap:(CGPoint)arg1 ;
-(void)showLoadingIndicator;
-(void)hideLoadingIndicator;
-(void)dealloc;
-(void)layoutSubviews;
-(void)scrollViewWillBeginDragging:(id)arg1 ;
-(void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(char)arg2 ;
-(id)viewForZoomingInScrollView:(id)arg1 ;
-(void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2 ;
-(void)prepareForReuse;
-(unsigned)index;
-(void)displayImage;
-(void)setIndex:(unsigned)arg1 ;
-(void)setMaxMinZoomScalesForCurrentBounds;
-(id<MWPhoto>)photo;
-(void)setPhoto:(id<MWPhoto>)arg1 ;
-(void)setSelectedButton:(UIButton *)arg1 ;
-(UIButton *)selectedButton;
@end

