/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSArray;

@interface PlaySettingsManager : NSObject {

	NSArray* _playSettingsArray;

}
-(id)findPlaySettingsByScriptTitle:(id)arg1 ;
-(char)ifPlayDirectly:(id)arg1 ;
-(char)hasPlaySettings:(id)arg1 ;
-(void)reloadData;
-(id)init;
@end

