/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <UIKit/UIScrollView.h>
#import <UIKit/UIScrollViewDelegate.h>

@protocol PSTCollectionViewDataSource;
@class PSTCollectionViewLayout, UIView, NSMutableSet, NSMutableDictionary, PSTCollectionReusableView, NSString, NSIndexPath, PSTCollectionViewData, NSMutableArray, NSArray, UITouch, PSTCollectionViewExt, NSDictionary;

@interface PSTCollectionView : UIScrollView <UIScrollViewDelegate> {

	PSTCollectionViewLayout* _layout;
	id<PSTCollectionViewDataSource> _dataSource;
	UIView* _backgroundView;
	NSMutableSet* _indexPathsForSelectedItems;
	NSMutableDictionary* _cellReuseQueues;
	NSMutableDictionary* _supplementaryViewReuseQueues;
	NSMutableDictionary* _decorationViewReuseQueues;
	NSMutableSet* _indexPathsForHighlightedItems;
	int _reloadingSuspendedCount;
	PSTCollectionReusableView* _firstResponderView;
	UIView* _newContentView;
	int _firstResponderViewType;
	NSString* _firstResponderViewKind;
	NSIndexPath* _firstResponderIndexPath;
	NSMutableDictionary* _allVisibleViewsDict;
	NSIndexPath* _pendingSelectionIndexPath;
	NSMutableSet* _pendingDeselectionIndexPaths;
	PSTCollectionViewData* _collectionViewData;
	id _update;
	CGRect _visibleBoundRects;
	CGRect _preRotationBounds;
	CGPoint _rotationBoundsOffset;
	int _rotationAnimationCount;
	int _updateCount;
	NSMutableArray* _insertItems;
	NSMutableArray* _deleteItems;
	NSMutableArray* _reloadItems;
	NSMutableArray* _moveItems;
	NSArray* _originalInsertItems;
	NSArray* _originalDeleteItems;
	UITouch* _currentTouch;
	/*^block*/id _updateCompletionHandler;
	NSMutableDictionary* _cellClassDict;
	NSMutableDictionary* _cellNibDict;
	NSMutableDictionary* _supplementaryViewClassDict;
	NSMutableDictionary* _supplementaryViewNibDict;
	NSMutableDictionary* _cellNibExternalObjectsTables;
	NSMutableDictionary* _supplementaryViewNibExternalObjectsTables;
	struct {
		unsigned delegateShouldHighlightItemAtIndexPath : 1;
		unsigned delegateDidHighlightItemAtIndexPath : 1;
		unsigned delegateDidUnhighlightItemAtIndexPath : 1;
		unsigned delegateShouldSelectItemAtIndexPath : 1;
		unsigned delegateShouldDeselectItemAtIndexPath : 1;
		unsigned delegateDidSelectItemAtIndexPath : 1;
		unsigned delegateDidDeselectItemAtIndexPath : 1;
		unsigned delegateSupportsMenus : 1;
		unsigned delegateDidEndDisplayingCell : 1;
		unsigned delegateDidEndDisplayingSupplementaryView : 1;
		unsigned dataSourceNumberOfSections : 1;
		unsigned dataSourceViewForSupplementaryElement : 1;
		unsigned reloadSkippedDuringSuspension : 1;
		unsigned scheduledUpdateVisibleCells : 1;
		unsigned scheduledUpdateVisibleCellLayoutAttributes : 1;
		unsigned allowsSelection : 1;
		unsigned allowsMultipleSelection : 1;
		unsigned updating : 1;
		unsigned fadeCellsForBoundsChange : 1;
		unsigned updatingLayout : 1;
		unsigned needsReload : 1;
		unsigned reloading : 1;
		unsigned skipLayoutDuringSnapshotting : 1;
		unsigned layoutInvalidatedSinceLastCellUpdate : 1;
		unsigned doneFirstLayout : 1;
	}  _collectionViewFlags;
	CGPoint _lastLayoutOffset;
	char filler[200];

}

@property (nonatomic,retain) PSTCollectionViewLayout * collectionViewLayout;              //@synthesize layout=_layout - In the implementation block
@property (assign,nonatomic) id<PSTCollectionViewDelegate> delegate; 
@property (assign,nonatomic) id<PSTCollectionViewDataSource> dataSource;                  //@synthesize dataSource=_dataSource - In the implementation block
@property (nonatomic,retain) UIView * backgroundView;                                     //@synthesize backgroundView=_backgroundView - In the implementation block
@property (assign,nonatomic) char allowsSelection; 
@property (assign,nonatomic) char allowsMultipleSelection; 
@property (nonatomic,retain) PSTCollectionViewData * collectionViewData;                  //@synthesize collectionViewData=_collectionViewData - In the implementation block
@property (nonatomic,readonly) PSTCollectionViewExt * extVars; 
@property (nonatomic,readonly) id currentUpdate;                                          //@synthesize update=_update - In the implementation block
@property (nonatomic,readonly) NSDictionary * visibleViewsDict;                           //@synthesize allVisibleViewsDict=_allVisibleViewsDict - In the implementation block
@property (assign,nonatomic) CGRect visibleBoundRects;                                    //@synthesize visibleBoundRects=_visibleBoundRects - In the implementation block
-(PSTCollectionViewExt *)extVars;
-(void)updateVisibleCellsNow:(char)arg1 ;
-(void)cellTouchCancelled;
-(CGRect)makeRect:(CGRect)arg1 toScrollPosition:(unsigned)arg2 ;
-(char)highlightItemAtIndexPath:(id)arg1 animated:(char)arg2 scrollPosition:(unsigned)arg3 notifyDelegate:(char)arg4 ;
-(char)unhighlightItemAtIndexPath:(id)arg1 animated:(char)arg2 notifyDelegate:(char)arg3 shouldCheckHighlight:(char)arg4 ;
-(char)unhighlightItemAtIndexPath:(id)arg1 animated:(char)arg2 notifyDelegate:(char)arg3 ;
-(void)userSelectedItemAtIndexPath:(id)arg1 ;
-(void)deselectItemAtIndexPath:(id)arg1 animated:(char)arg2 notifyDelegate:(char)arg3 ;
-(void)selectItemAtIndexPath:(id)arg1 animated:(char)arg2 scrollPosition:(unsigned)arg3 notifyDelegate:(char)arg4 ;
-(void)updateSections:(id)arg1 updateAction:(int)arg2 ;
-(id)arrayForUpdateAction:(int)arg1 ;
-(void)setupCellAnimations;
-(void)endItemAnimations;
-(void)updateRowsAtIndexPaths:(id)arg1 updateAction:(int)arg2 ;
-(id)createPreparedCellForItemAtIndexPath:(id)arg1 withLayoutAttributes:(id)arg2 ;
-(void)addControlledSubview:(id)arg1 ;
-(id)createPreparedSupplementaryViewForElementOfKind:(id)arg1 atIndexPath:(id)arg2 withLayoutAttributes:(id)arg3 ;
-(id)dequeueReusableOrCreateDecorationViewOfKind:(id)arg1 forIndexPath:(id)arg2 ;
-(void)reuseCell:(id)arg1 ;
-(void)reuseSupplementaryView:(id)arg1 ;
-(void)reuseDecorationView:(id)arg1 ;
-(PSTCollectionViewData *)collectionViewData;
-(void)queueReusableView:(id)arg1 inQueue:(id)arg2 withIdentifier:(id)arg3 ;
-(void)prepareLayoutForUpdates;
-(CGRect)visibleBoundRects;
-(void)suspendReloads;
-(void)updateWithItems:(id)arg1 ;
-(void)resumeReloads;
-(id)allCells;
-(id)currentUpdate;
-(NSDictionary *)visibleViewsDict;
-(void)setCollectionViewData:(PSTCollectionViewData *)arg1 ;
-(void)setVisibleBoundRects:(CGRect)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setDataSource:(id<PSTCollectionViewDataSource>)arg1 ;
-(void)setDelegate:(id<PSTCollectionViewDelegate>)arg1 ;
-(void)reloadData;
-(void)setFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setAllowsMultipleSelection:(char)arg1 ;
-(void)setBounds:(CGRect)arg1 ;
-(id)description;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewDidZoom:(id)arg1 ;
-(void)scrollViewWillBeginDragging:(id)arg1 ;
-(void)scrollViewWillEndDragging:(id)arg1 withVelocity:(CGPoint)arg2 targetContentOffset:(inout CGPoint*)arg3 ;
-(void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(char)arg2 ;
-(void)scrollViewWillBeginDecelerating:(id)arg1 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(void)scrollViewDidEndScrollingAnimation:(id)arg1 ;
-(id)viewForZoomingInScrollView:(id)arg1 ;
-(void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2 ;
-(void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(float)arg3 ;
-(char)scrollViewShouldScrollToTop:(id)arg1 ;
-(void)scrollViewDidScrollToTop:(id)arg1 ;
-(char)allowsMultipleSelection;
-(id<PSTCollectionViewDataSource>)dataSource;
-(id<PSTCollectionViewDelegate>)delegate;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)awakeFromNib;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(int)numberOfSections;
-(id)indexPathForCell:(id)arg1 ;
-(id)visibleCells;
-(void)setAllowsSelection:(char)arg1 ;
-(char)allowsSelection;
-(void)setBackgroundView:(UIView *)arg1 ;
-(void)moveSection:(int)arg1 toSection:(int)arg2 ;
-(UIView *)backgroundView;
-(id)initWithFrame:(CGRect)arg1 collectionViewLayout:(id)arg2 ;
-(id)indexPathsForSelectedItems;
-(void)selectItemAtIndexPath:(id)arg1 animated:(char)arg2 scrollPosition:(unsigned)arg3 ;
-(int)numberOfItemsInSection:(int)arg1 ;
-(id)dequeueReusableCellWithReuseIdentifier:(id)arg1 forIndexPath:(id)arg2 ;
-(id)dequeueReusableSupplementaryViewOfKind:(id)arg1 withReuseIdentifier:(id)arg2 forIndexPath:(id)arg3 ;
-(void)scrollToItemAtIndexPath:(id)arg1 atScrollPosition:(unsigned)arg2 animated:(char)arg3 ;
-(id)indexPathsForVisibleItems;
-(id)cellForItemAtIndexPath:(id)arg1 ;
-(void)registerClass:(Class)arg1 forCellWithReuseIdentifier:(id)arg2 ;
-(void)insertItemsAtIndexPaths:(id)arg1 ;
-(PSTCollectionViewLayout *)collectionViewLayout;
-(void)registerClass:(Class)arg1 forSupplementaryViewOfKind:(id)arg2 withReuseIdentifier:(id)arg3 ;
-(id)layoutAttributesForItemAtIndexPath:(id)arg1 ;
-(void)invalidateLayout;
-(void)deleteItemsAtIndexPaths:(id)arg1 ;
-(void)performBatchUpdates:(/*^block*/id)arg1 completion:(/*^block*/id)arg2 ;
-(id)indexPathForItemAtPoint:(CGPoint)arg1 ;
-(void)deselectItemAtIndexPath:(id)arg1 animated:(char)arg2 ;
-(id)layoutAttributesForSupplementaryElementOfKind:(id)arg1 atIndexPath:(id)arg2 ;
-(void)setCollectionViewLayout:(PSTCollectionViewLayout *)arg1 ;
-(void)setCollectionViewLayout:(id)arg1 animated:(char)arg2 ;
-(void)registerNib:(id)arg1 forCellWithReuseIdentifier:(id)arg2 ;
-(void)registerNib:(id)arg1 forSupplementaryViewOfKind:(id)arg2 withReuseIdentifier:(id)arg3 ;
-(void)insertSections:(id)arg1 ;
-(void)deleteSections:(id)arg1 ;
-(void)reloadSections:(id)arg1 ;
-(void)reloadItemsAtIndexPaths:(id)arg1 ;
-(void)moveItemAtIndexPath:(id)arg1 toIndexPath:(id)arg2 ;
@end

