/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSIndexPath;

@interface PSTCollectionViewUpdateItem : NSObject {

	NSIndexPath* _initialIndexPath;
	NSIndexPath* _finalIndexPath;
	int _updateAction;
	id _gap;

}

@property (nonatomic,readonly) NSIndexPath * indexPathBeforeUpdate;              //@synthesize initialIndexPath=_initialIndexPath - In the implementation block
@property (nonatomic,readonly) NSIndexPath * indexPathAfterUpdate;               //@synthesize finalIndexPath=_finalIndexPath - In the implementation block
@property (nonatomic,readonly) int updateAction;                                 //@synthesize updateAction=_updateAction - In the implementation block
-(void)setNewIndexPath:(id)arg1 ;
-(id)description;
-(int)action;
-(int)inverseCompareIndexPaths:(id)arg1 ;
-(int)compareIndexPaths:(id)arg1 ;
-(id)indexPath;
-(char)isSectionOperation;
-(id)newIndexPath;
-(id)initWithOldIndexPath:(id)arg1 newIndexPath:(id)arg2 ;
-(void)setGap:(id)arg1 ;
-(id)gap;
-(id)initWithAction:(int)arg1 forIndexPath:(id)arg2 ;
-(id)initWithInitialIndexPath:(id)arg1 finalIndexPath:(id)arg2 updateAction:(int)arg3 ;
-(int)updateAction;
-(NSIndexPath *)indexPathBeforeUpdate;
-(NSIndexPath *)indexPathAfterUpdate;
@end

