/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <AutoTouch/PSTCollectionReusableView.h>

@class UIView, UILongPressGestureRecognizer;

@interface PSTCollectionViewCell : PSTCollectionReusableView {

	UIView* _contentView;
	UIView* _backgroundView;
	UIView* _selectedBackgroundView;
	UILongPressGestureRecognizer* _menuGesture;
	id _selectionSegueTemplate;
	id _highlightingSupport;
	struct {
		unsigned selected : 1;
		unsigned highlighted : 1;
		unsigned showingMenu : 1;
		unsigned clearSelectionWhenMenuDisappears : 1;
		unsigned waitingForSelectionAnimationHalfwayPoint : 1;
	}  _collectionCellFlags;
	char _selected;
	char _highlighted;

}

@property (nonatomic,readonly) UIView * contentView;                             //@synthesize contentView=_contentView - In the implementation block
@property (assign,getter=isSelected,nonatomic) char selected; 
@property (assign,getter=isHighlighted,nonatomic) char highlighted; 
@property (nonatomic,retain) UIView * backgroundView;                            //@synthesize backgroundView=_backgroundView - In the implementation block
@property (nonatomic,retain) UIView * selectedBackgroundView;                    //@synthesize selectedBackgroundView=_selectedBackgroundView - In the implementation block
-(void)performSelectionSegue;
-(void)menuGesture:(id)arg1 ;
-(void)updateBackgroundView:(char)arg1 ;
-(void)setHighlighted:(char)arg1 forViews:(id)arg2 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(UIView *)contentView;
-(void)setHighlighted:(char)arg1 ;
-(char)isHighlighted;
-(char)isSelected;
-(void)setBackgroundView:(UIView *)arg1 ;
-(void)prepareForReuse;
-(void)setSelected:(char)arg1 ;
-(UIView *)backgroundView;
-(void)setSelectedBackgroundView:(UIView *)arg1 ;
-(UIView *)selectedBackgroundView;
@end

