/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <CoreFoundation/NSCopying.h>

@class NSIndexPath, NSString;

@interface PSTCollectionViewLayoutAttributes : NSObject <NSCopying> {

	struct {
		unsigned isCellKind : 1;
		unsigned isDecorationView : 1;
		unsigned isHidden : 1;
	}  _layoutFlags;
	char filler[20];
	char _hidden;
	float _alpha;
	int _zIndex;
	NSIndexPath* _indexPath;
	unsigned _elementCategory;
	NSString* _elementKind;
	CGPoint _center;
	CGSize _size;
	CGRect _frame;
	CATransform3D _transform3D;

}

@property (assign,nonatomic) CGRect frame;                             //@synthesize frame=_frame - In the implementation block
@property (assign,nonatomic) CGPoint center;                           //@synthesize center=_center - In the implementation block
@property (assign,nonatomic) CGSize size;                              //@synthesize size=_size - In the implementation block
@property (assign,nonatomic) CATransform3D transform3D;                //@synthesize transform3D=_transform3D - In the implementation block
@property (assign,nonatomic) float alpha;                              //@synthesize alpha=_alpha - In the implementation block
@property (assign,nonatomic) int zIndex;                               //@synthesize zIndex=_zIndex - In the implementation block
@property (assign,getter=isHidden,nonatomic) char hidden;              //@synthesize hidden=_hidden - In the implementation block
@property (nonatomic,retain) NSIndexPath * indexPath;                  //@synthesize indexPath=_indexPath - In the implementation block
@property (assign,nonatomic) unsigned elementCategory;                 //@synthesize elementCategory=_elementCategory - In the implementation block
@property (nonatomic,copy) NSString * elementKind;                     //@synthesize elementKind=_elementKind - In the implementation block
+(id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 withIndexPath:(id)arg2 ;
+(id)layoutAttributesForCellWithIndexPath:(id)arg1 ;
+(id)layoutAttributesForDecorationViewOfKind:(id)arg1 withIndexPath:(id)arg2 ;
-(void)setElementKind:(NSString *)arg1 ;
-(void)setElementCategory:(unsigned)arg1 ;
-(unsigned)elementCategory;
-(char)isDecorationView;
-(char)isSupplementaryView;
-(char)isCell;
-(CGSize)size;
-(char)isHidden;
-(float)alpha;
-(void)setHidden:(char)arg1 ;
-(void)setAlpha:(float)arg1 ;
-(id)init;
-(void)setFrame:(CGRect)arg1 ;
-(CGRect)frame;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setSize:(CGSize)arg1 ;
-(CGPoint)center;
-(void)setCenter:(CGPoint)arg1 ;
-(NSIndexPath *)indexPath;
-(void)forwardInvocation:(id)arg1 ;
-(void)updateFrame;
-(unsigned)representedElementCategory;
-(CATransform3D)transform3D;
-(int)zIndex;
-(void)setIndexPath:(NSIndexPath *)arg1 ;
-(void)setTransform3D:(CATransform3D)arg1 ;
-(id)representedElementKind;
-(void)setZIndex:(int)arg1 ;
-(NSString *)elementKind;
@end

