/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <UIKit/UIViewController.h>
#import <AutoTouch/PSTCollectionViewDelegate.h>
#import <AutoTouch/PSTCollectionViewDataSource.h>

@class PSTCollectionViewLayout, PSTCollectionView;

@interface PSTCollectionViewController : UIViewController <PSTCollectionViewDelegate, PSTCollectionViewDataSource> {

	PSTCollectionViewLayout* _layout;
	PSTCollectionView* _collectionView;
	struct {
		unsigned clearsSelectionOnViewWillAppear : 1;
		unsigned appearsFirstTime : 1;
	}  _collectionViewControllerFlags;
	char filler[100];

}

@property (nonatomic,retain) PSTCollectionView * collectionView;                //@synthesize collectionView=_collectionView - In the implementation block
@property (assign,nonatomic) char clearsSelectionOnViewWillAppear; 
@property (nonatomic,retain) PSTCollectionViewLayout * layout;                  //@synthesize layout=_layout - In the implementation block
-(id)initWithCoder:(id)arg1 ;
-(PSTCollectionViewLayout *)layout;
-(PSTCollectionView *)collectionView;
-(int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2 ;
-(id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2 ;
-(void)loadView;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidLoad;
-(void)setLayout:(PSTCollectionViewLayout *)arg1 ;
-(void)setClearsSelectionOnViewWillAppear:(char)arg1 ;
-(char)clearsSelectionOnViewWillAppear;
-(id)initWithCollectionViewLayout:(id)arg1 ;
-(void)setCollectionView:(PSTCollectionView *)arg1 ;
@end

