/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <CoreFoundation/NSCopying.h>

@class NSIndexPath, NSString;

@interface PSTCollectionViewItemKey : NSObject <NSCopying> {

	unsigned _type;
	NSIndexPath* _indexPath;
	NSString* _identifier;

}

@property (assign,nonatomic) unsigned type;                        //@synthesize type=_type - In the implementation block
@property (nonatomic,retain) NSIndexPath * indexPath;              //@synthesize indexPath=_indexPath - In the implementation block
@property (nonatomic,retain) NSString * identifier;                //@synthesize identifier=_identifier - In the implementation block
+(id)collectionItemKeyForCellWithIndexPath:(id)arg1 ;
+(id)collectionItemKeyForLayoutAttributes:(id)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(void)setType:(unsigned)arg1 ;
-(unsigned)type;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSIndexPath *)indexPath;
-(NSString *)identifier;
-(void)setIdentifier:(NSString *)arg1 ;
-(void)setIndexPath:(NSIndexPath *)arg1 ;
@end

