/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <CoreFoundation/NSCoding.h>

@class PSTCollectionView, NSMutableDictionary, NSMutableIndexSet, NSDictionary;

@interface PSTCollectionViewLayout : NSObject <NSCoding> {

	PSTCollectionView* _collectionView;
	CGSize _collectionViewBoundsSize;
	NSMutableDictionary* _initialAnimationLayoutAttributesDict;
	NSMutableDictionary* _finalAnimationLayoutAttributesDict;
	NSMutableIndexSet* _deletedSectionsSet;
	NSMutableIndexSet* _insertedSectionsSet;
	NSMutableDictionary* _decorationViewClassDict;
	NSMutableDictionary* _decorationViewNibDict;
	NSMutableDictionary* _decorationViewExternalObjectsTables;
	char filler[200];

}

@property (assign,nonatomic) PSTCollectionView * collectionView;                                     //@synthesize collectionView=_collectionView - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * decorationViewClassDict;                          //@synthesize decorationViewClassDict=_decorationViewClassDict - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * decorationViewNibDict;                            //@synthesize decorationViewNibDict=_decorationViewNibDict - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * decorationViewExternalObjectsTables;              //@synthesize decorationViewExternalObjectsTables=_decorationViewExternalObjectsTables - In the implementation block
+(Class)layoutAttributesClass;
-(NSDictionary *)decorationViewNibDict;
-(NSDictionary *)decorationViewExternalObjectsTables;
-(NSDictionary *)decorationViewClassDict;
-(id)initialLayoutAttributesForInsertedSupplementaryElementOfKind:(id)arg1 atIndexPath:(id)arg2 ;
-(id)finalLayoutAttributesForDeletedSupplementaryElementOfKind:(id)arg1 atIndexPath:(id)arg2 ;
-(void)setCollectionViewBoundsSize:(CGSize)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(void)awakeFromNib;
-(PSTCollectionView *)collectionView;
-(CGSize)collectionViewContentSize;
-(id)layoutAttributesForItemAtIndexPath:(id)arg1 ;
-(void)invalidateLayout;
-(id)layoutAttributesForElementsInRect:(CGRect)arg1 ;
-(id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2 ;
-(void)prepareLayout;
-(char)shouldInvalidateLayoutForBoundsChange:(CGRect)arg1 ;
-(id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)arg1 ;
-(id)initialLayoutAttributesForAppearingItemAtIndexPath:(id)arg1 ;
-(id)layoutAttributesForDecorationViewOfKind:(id)arg1 atIndexPath:(id)arg2 ;
-(CGPoint)targetContentOffsetForProposedContentOffset:(CGPoint)arg1 withScrollingVelocity:(CGPoint)arg2 ;
-(void)prepareForCollectionViewUpdates:(id)arg1 ;
-(void)finalizeCollectionViewUpdates;
-(void)registerClass:(Class)arg1 forDecorationViewOfKind:(id)arg2 ;
-(void)registerNib:(id)arg1 forDecorationViewOfKind:(id)arg2 ;
-(void)setCollectionView:(PSTCollectionView *)arg1 ;
@end

