/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <AutoTouch/AutoTouch-Structs.h>
@class PSTCollectionView, PSTCollectionViewLayout, NSArray;

@interface PSTCollectionViewData : NSObject {

	CGRect _validLayoutRect;
	int _numItems;
	int _numSections;
	int* _sectionItemCounts;
	CGSize _contentSize;
	struct {
		unsigned contentSizeIsValid : 1;
		unsigned itemCountsAreValid : 1;
		unsigned layoutIsPrepared : 1;
	}  _collectionViewDataFlags;
	PSTCollectionView* _collectionView;
	PSTCollectionViewLayout* _layout;
	NSArray* _cachedLayoutAttributes;

}

@property (readonly) char layoutIsPrepared; 
@property (assign,nonatomic) PSTCollectionView * collectionView;              //@synthesize collectionView=_collectionView - In the implementation block
@property (assign,nonatomic) PSTCollectionViewLayout * layout;                //@synthesize layout=_layout - In the implementation block
@property (nonatomic,retain) NSArray * cachedLayoutAttributes;                //@synthesize cachedLayoutAttributes=_cachedLayoutAttributes - In the implementation block
-(void)prepareToLoadData;
-(void)validateItemCounts;
-(void)setCachedLayoutAttributes:(NSArray *)arg1 ;
-(NSArray *)cachedLayoutAttributes;
-(void)updateItemCounts;
-(void)setLayoutIsPrepared:(char)arg1 ;
-(void)dealloc;
-(id)description;
-(void)invalidate;
-(int)numberOfSections;
-(PSTCollectionViewLayout *)layout;
-(PSTCollectionView *)collectionView;
-(int)numberOfItemsInSection:(int)arg1 ;
-(void)setLayout:(PSTCollectionViewLayout *)arg1 ;
-(int)numberOfItems;
-(id)layoutAttributesForElementsInRect:(CGRect)arg1 ;
-(int)numberOfItemsBeforeSection:(int)arg1 ;
-(unsigned)globalIndexForItemAtIndexPath:(id)arg1 ;
-(char)layoutIsPrepared;
-(CGRect)collectionViewContentRect;
-(void)validateLayoutInRect:(CGRect)arg1 ;
-(id)initWithCollectionView:(id)arg1 layout:(id)arg2 ;
-(id)indexPathForItemAtGlobalIndex:(int)arg1 ;
-(void)setCollectionView:(PSTCollectionView *)arg1 ;
-(CGRect)rectForItemAtIndexPath:(id)arg1 ;
@end

