/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <UIKit/UIView.h>

@class PSTCollectionViewLayoutAttributes, NSString, PSTCollectionView;

@interface PSTCollectionReusableView : UIView {

	PSTCollectionViewLayoutAttributes* _layoutAttributes;
	NSString* _reuseIdentifier;
	PSTCollectionView* _collectionView;
	struct {
		unsigned inUpdateAnimation : 1;
	}  _reusableViewFlags;
	char filler[50];

}

@property (nonatomic,copy) NSString * reuseIdentifier;                                          //@synthesize reuseIdentifier=_reuseIdentifier - In the implementation block
@property (assign,nonatomic) PSTCollectionView * collectionView;                                //@synthesize collectionView=_collectionView - In the implementation block
@property (nonatomic,retain) PSTCollectionViewLayoutAttributes * layoutAttributes;              //@synthesize layoutAttributes=_layoutAttributes - In the implementation block
-(char)isInUpdateAnimation;
-(void)setInUpdateAnimation:(char)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)awakeFromNib;
-(NSString *)reuseIdentifier;
-(void)prepareForReuse;
-(void)setReuseIdentifier:(NSString *)arg1 ;
-(PSTCollectionView *)collectionView;
-(void)applyLayoutAttributes:(id)arg1 ;
-(void)willTransitionFromLayout:(id)arg1 toLayout:(id)arg2 ;
-(void)didTransitionFromLayout:(id)arg1 toLayout:(id)arg2 ;
-(void)setCollectionView:(PSTCollectionView *)arg1 ;
-(PSTCollectionViewLayoutAttributes *)layoutAttributes;
-(void)setLayoutAttributes:(PSTCollectionViewLayoutAttributes *)arg1 ;
@end

