/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <AutoTouch/AutoTouch-Structs.h>
@class PSTGridLayoutSection, PSTGridLayoutRow;

@interface PSTGridLayoutItem : NSObject {

	PSTGridLayoutSection* _section;
	PSTGridLayoutRow* _rowObject;
	CGRect _itemFrame;

}

@property (assign,nonatomic) PSTGridLayoutSection * section;              //@synthesize section=_section - In the implementation block
@property (assign,nonatomic) PSTGridLayoutRow * rowObject;                //@synthesize rowObject=_rowObject - In the implementation block
@property (assign,nonatomic) CGRect itemFrame;                            //@synthesize itemFrame=_itemFrame - In the implementation block
-(id)description;
-(PSTGridLayoutSection *)section;
-(void)setItemFrame:(CGRect)arg1 ;
-(CGRect)itemFrame;
-(PSTGridLayoutRow *)rowObject;
-(void)setSection:(PSTGridLayoutSection *)arg1 ;
-(void)setRowObject:(PSTGridLayoutRow *)arg1 ;
@end

