/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <AutoTouch/AutoTouch-Structs.h>
@interface Reachability : NSObject {

	char reachableOnWWAN;
	SCNetworkReachabilityRef reachabilityRef;
	dispatch_queue_sRef reachabilitySerialQueue;
	/*^block*/id reachableBlock;
	/*^block*/id unreachableBlock;
	id reachabilityObject;

}

@property (nonatomic,copy) id reachableBlock; 
@property (nonatomic,copy) id unreachableBlock; 
@property (assign,nonatomic) char reachableOnWWAN; 
@property (assign,nonatomic) SCNetworkReachabilityRef reachabilityRef; 
@property (assign,nonatomic) dispatch_queue_sRef reachabilitySerialQueue; 
@property (nonatomic,retain) id reachabilityObject; 
+(id)reachabilityWithHostname:(id)arg1 ;
+(id)reachabilityWithHostName:(id)arg1 ;
+(id)reachabilityWithAddress:(const sockaddr_in*)arg1 ;
+(id)reachabilityForInternetConnection;
+(id)reachabilityForLocalWiFi;
-(id)initWithReachabilityRef:(SCNetworkReachabilityRef)arg1 ;
-(void)setReachableOnWWAN:(char)arg1 ;
-(void)stopNotifier;
-(void)setReachableBlock:(id)arg1 ;
-(void)setUnreachableBlock:(id)arg1 ;
-(void)setReachabilityObject:(id)arg1 ;
-(void)setReachabilitySerialQueue:(dispatch_queue_sRef)arg1 ;
-(dispatch_queue_sRef)reachabilitySerialQueue;
-(char)reachableOnWWAN;
-(char)isReachableWithFlags:(unsigned)arg1 ;
-(char)isReachableViaWiFi;
-(unsigned)reachabilityFlags;
-(id)reachableBlock;
-(id)unreachableBlock;
-(char)startNotifier;
-(char)isReachableViaWWAN;
-(char)isConnectionRequired;
-(char)isConnectionOnDemand;
-(char)isInterventionRequired;
-(id)currentReachabilityString;
-(id)currentReachabilityFlags;
-(void)reachabilityChanged:(unsigned)arg1 ;
-(id)reachabilityObject;
-(void)dealloc;
-(id)description;
-(char)connectionRequired;
-(SCNetworkReachabilityRef)reachabilityRef;
-(void)setReachabilityRef:(SCNetworkReachabilityRef)arg1 ;
-(int)currentReachabilityStatus;
-(char)isReachable;
@end

