/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <AutoTouch/AutoTouch-Structs.h>
@class RNCryptorEngine, NSMutableData, NSError;

@interface RNCryptor : NSObject {

	char _finished;
	unsigned char _options;
	dispatch_queue_sRef _responseQueue;
	RNCryptorEngine* _engine;
	NSMutableData* __outData;
	dispatch_queue_sRef _queue;
	unsigned __HMACLength;
	NSError* _error;
	/*^block*/id _handler;

}

@property (nonatomic,retain) NSError * error;                                //@synthesize error=_error - In the implementation block
@property (assign,getter=isFinished,nonatomic) char finished;                //@synthesize finished=_finished - In the implementation block
@property (nonatomic,copy) id handler;                                       //@synthesize handler=_handler - In the implementation block
@property (assign,nonatomic) dispatch_queue_sRef responseQueue;              //@synthesize responseQueue=_responseQueue - In the implementation block
@property (nonatomic,retain) RNCryptorEngine * engine;                       //@synthesize engine=_engine - In the implementation block
@property (assign,nonatomic) dispatch_queue_sRef queue;                      //@synthesize queue=_queue - In the implementation block
@property (nonatomic,readonly) NSMutableData * outData;                      //@synthesize _outData=__outData - In the implementation block
@property (assign,nonatomic) unsigned HMACLength;                            //@synthesize _HMACLength=__HMACLength - In the implementation block
@property (assign,nonatomic) unsigned char options;                          //@synthesize options=_options - In the implementation block
+(id)synchronousResultForCryptor:(id)arg1 data:(id)arg2 error:(id*)arg3 ;
+(id)keyForPassword:(id)arg1 salt:(id)arg2 settings:(RNCryptorKeyDerivationSettings)arg3 ;
+(id)randomDataOfLength:(unsigned long)arg1 ;
-(void)setResponseQueue:(dispatch_queue_sRef)arg1 ;
-(dispatch_queue_sRef)responseQueue;
-(NSMutableData *)outData;
-(unsigned)HMACLength;
-(void)cleanupAndNotifyWithError:(id)arg1 ;
-(char)hasHMAC;
-(void)setHMACLength:(unsigned)arg1 ;
-(id)initWithHandler:(/*^block*/id)arg1 ;
-(void)setError:(NSError *)arg1 ;
-(void)dealloc;
-(void)setOptions:(unsigned char)arg1 ;
-(unsigned char)options;
-(void)setHandler:(id)arg1 ;
-(id)handler;
-(char)isFinished;
-(void)finish;
-(RNCryptorEngine *)engine;
-(void)setEngine:(RNCryptorEngine *)arg1 ;
-(void)addData:(id)arg1 ;
-(dispatch_queue_sRef)queue;
-(void)setQueue:(dispatch_queue_sRef)arg1 ;
-(void)setFinished:(char)arg1 ;
-(NSError *)error;
@end

