/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <AutoTouch/AutoTouch-Structs.h>
@class NSMutableData;

@interface RNCryptorEngine : NSObject {

	CCCryptorRef __cryptor;
	NSMutableData* __buffer;

}

@property (nonatomic,readonly) CCCryptorRef cryptor;                //@synthesize _cryptor=__cryptor - In the implementation block
@property (nonatomic,readonly) NSMutableData * buffer;              //@synthesize _buffer=__buffer - In the implementation block
-(CCCryptorRef)cryptor;
-(id)initWithOperation:(unsigned)arg1 settings:(RNCryptorSettings)arg2 key:(id)arg3 IV:(id)arg4 error:(id*)arg5 ;
-(id)addData:(id)arg1 error:(id*)arg2 ;
-(id)finishWithError:(id*)arg1 ;
-(void)dealloc;
-(NSMutableData *)buffer;
@end

