/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <AutoTouch/RNCryptor.h>

@class NSMutableData, NSData, NSString;

@interface RNDecryptor : RNCryptor {

	SCD_Struct_RN25 _HMACContext;
	NSMutableData* __inData;
	char _hasV1HMAC;
	NSData* _encryptionKey;
	NSData* _HMACKey;
	NSString* _password;
	RNCryptorSettings _settings;

}

@property (nonatomic,readonly) NSMutableData * inData; 
@property (nonatomic,copy) NSData * encryptionKey;                    //@synthesize encryptionKey=_encryptionKey - In the implementation block
@property (nonatomic,copy) NSData * HMACKey;                          //@synthesize HMACKey=_HMACKey - In the implementation block
@property (nonatomic,copy) NSString * password;                       //@synthesize password=_password - In the implementation block
@property (assign,nonatomic) char hasV1HMAC;                          //@synthesize hasV1HMAC=_hasV1HMAC - In the implementation block
@property (assign,nonatomic) RNCryptorSettings settings;              //@synthesize settings=_settings - In the implementation block
+(id)decryptData:(id)arg1 withPassword:(id)arg2 error:(id*)arg3 ;
+(id)decryptData:(id)arg1 withSettings:(RNCryptorSettings)arg2 encryptionKey:(id)arg3 HMACKey:(id)arg4 error:(id*)arg5 ;
+(id)decryptData:(id)arg1 withSettings:(RNCryptorSettings)arg2 password:(id)arg3 error:(id*)arg4 ;
+(id)decryptData:(id)arg1 withEncryptionKey:(id)arg2 HMACKey:(id)arg3 error:(id*)arg4 ;
-(id)initWithPassword:(id)arg1 handler:(/*^block*/id)arg2 ;
-(NSMutableData *)inData;
-(void)decryptData:(id)arg1 ;
-(char)updateOptionsForPreamble:(id)arg1 ;
-(void)setEncryptionKey:(NSData *)arg1 ;
-(void)setHMACKey:(NSData *)arg1 ;
-(NSData *)encryptionKey;
-(NSData *)HMACKey;
-(char)hasV1HMAC;
-(void)setHasV1HMAC:(char)arg1 ;
-(id)initWithEncryptionKey:(id)arg1 HMACKey:(id)arg2 handler:(/*^block*/id)arg3 ;
-(void)consumeHeaderFromData:(id)arg1 ;
-(NSString *)password;
-(void)setPassword:(NSString *)arg1 ;
-(void)setSettings:(RNCryptorSettings)arg1 ;
-(RNCryptorSettings)settings;
-(void)finish;
-(void)addData:(id)arg1 ;
@end

