/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <AutoTouch/RNDecryptor.h>

@class NSString;

@interface RNOpenSSLDecryptor : RNDecryptor {

	NSString* _password;
	RNCryptorSettings _settings;

}

@property (assign,nonatomic) RNCryptorSettings settings;              //@synthesize settings=_settings - In the implementation block
@property (nonatomic,copy) NSString * password;                       //@synthesize password=_password - In the implementation block
+(id)decryptData:(id)arg1 withPassword:(id)arg2 error:(id*)arg3 ;
+(id)decryptData:(id)arg1 withSettings:(RNCryptorSettings)arg2 password:(id)arg3 error:(id*)arg4 ;
+(id)decryptData:(id)arg1 withSettings:(RNCryptorSettings)arg2 encryptionKey:(id)arg3 IV:(id)arg4 error:(id*)arg5 ;
+(id)decryptData:(id)arg1 withEncryptionKey:(id)arg2 HMACKey:(id)arg3 error:(id*)arg4 ;
-(id)initWithSettings:(RNCryptorSettings)arg1 password:(id)arg2 handler:(/*^block*/id)arg3 ;
-(id)initWithPassword:(id)arg1 handler:(/*^block*/id)arg2 ;
-(id)initWithSettings:(RNCryptorSettings)arg1 encryptionKey:(id)arg2 IV:(id)arg3 handler:(/*^block*/id)arg4 ;
-(id)initWithEncryptionKey:(id)arg1 HMACKey:(id)arg2 handler:(/*^block*/id)arg3 ;
-(void)consumeHeaderFromData:(id)arg1 ;
-(NSString *)password;
-(void)setPassword:(NSString *)arg1 ;
-(void)setSettings:(RNCryptorSettings)arg1 ;
-(RNCryptorSettings)settings;
@end

