/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <AutoTouch/RNEncryptor.h>

@class NSData;

@interface RNOpenSSLEncryptor : RNEncryptor {

	NSData* _encryptionSalt;

}

@property (nonatomic,retain) NSData * encryptionSalt;              //@synthesize encryptionSalt=_encryptionSalt - In the implementation block
+(id)encryptData:(id)arg1 withSettings:(RNCryptorSettings)arg2 encryptionKey:(id)arg3 IV:(id)arg4 error:(id*)arg5 ;
-(id)initWithSettings:(RNCryptorSettings)arg1 password:(id)arg2 handler:(/*^block*/id)arg3 ;
-(id)initWithSettings:(RNCryptorSettings)arg1 encryptionKey:(id)arg2 HMACKey:(id)arg3 handler:(/*^block*/id)arg4 ;
-(void)setEncryptionSalt:(NSData *)arg1 ;
-(NSData *)encryptionSalt;
-(id)initWithSettings:(RNCryptorSettings)arg1 encryptionKey:(id)arg2 IV:(id)arg3 handler:(/*^block*/id)arg4 ;
-(id)header;
@end

