/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewController.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITextFieldDelegate.h>
#import <UIKit/UIAlertViewDelegate.h>

@class UITextField, UIPlaceHolderTextView, NSMutableSet, UIBarButtonItem, NSString;

@interface ScriptUploadViewController : UITableViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate, UIAlertViewDelegate> {

	UITextField* titleTextField;
	UITextField* priceTextField;
	UIPlaceHolderTextView* descriptionTextView;
	NSMutableSet* selectedScreenSizes;
	UIBarButtonItem* rightButton;
	NSString* _scriptPath;

}

@property (nonatomic,retain) NSString * scriptPath;              //@synthesize scriptPath=_scriptPath - In the implementation block
-(void)viewTapped:(id)arg1 ;
-(void)uploadToStore;
-(void)setScriptPath:(NSString *)arg1 ;
-(id)init;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2 ;
-(void)didReceiveMemoryWarning;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(void)viewDidLoad;
-(void)done;
-(NSString *)scriptPath;
@end

