/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <UIKit/UIViewController.h>
#import <UIKit/UITextViewDelegate.h>
#import <UIKit/UIAlertViewDelegate.h>

@class HelpViewController, UITextView, Script, NSString, UIBarButtonItem;

@interface ScriptEditViewController : UIViewController <UITextViewDelegate, UIAlertViewDelegate> {

	HelpViewController* _helpViewController;
	char _editable;
	UITextView* _textView;
	Script* _script;
	NSString* _dirPath;
	UIBarButtonItem* _saveButtonItem;
	UIBarButtonItem* _helpButtonItem;

}

@property (nonatomic,retain) UITextView * textView;                         //@synthesize textView=_textView - In the implementation block
@property (nonatomic,retain) Script * script;                               //@synthesize script=_script - In the implementation block
@property (nonatomic,retain) NSString * dirPath;                            //@synthesize dirPath=_dirPath - In the implementation block
@property (assign,nonatomic) char editable;                                 //@synthesize editable=_editable - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * saveButtonItem;              //@synthesize saveButtonItem=_saveButtonItem - In the implementation block
@property (nonatomic,retain) UIBarButtonItem * helpButtonItem;              //@synthesize helpButtonItem=_helpButtonItem - In the implementation block
-(void)help;
-(void)edit;
-(void)registerForKeyboardNotifications;
-(void)unregisterForKeyboardNotifications;
-(void)alertForSaveOrNot;
-(void)alertForScriptName;
-(void)saveScript:(id)arg1 ;
-(NSString *)dirPath;
-(void)setDirPath:(NSString *)arg1 ;
-(UIBarButtonItem *)saveButtonItem;
-(void)setSaveButtonItem:(UIBarButtonItem *)arg1 ;
-(UIBarButtonItem *)helpButtonItem;
-(void)setHelpButtonItem:(UIBarButtonItem *)arg1 ;
-(void)save;
-(void)dealloc;
-(void)didReceiveMemoryWarning;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(void)setTextView:(UITextView *)arg1 ;
-(void)viewDidLoad;
-(void)setEditable:(char)arg1 ;
-(void)keyboardDidShow:(id)arg1 ;
-(void)done;
-(char)editable;
-(UITextView *)textView;
-(Script *)script;
-(void)setScript:(Script *)arg1 ;
-(void)keyboardWillHide:(id)arg1 ;
@end

