/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UIActionSheetDelegate.h>
#import <UIKit/UIAlertViewDelegate.h>
#import <AutoTouch/MWPhotoBrowserDelegate.h>

@class PlaySettingsManager, NSArray, NSIndexPath, NSMutableArray, NSString, UITableView;

@interface ScriptsViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UIActionSheetDelegate, UIAlertViewDelegate, MWPhotoBrowserDelegate> {

	PlaySettingsManager* _playSettingsManager;
	NSArray* _activatorTriggersInDBArray;
	NSIndexPath* _lastDidSelectRowAtIndexPath;
	NSIndexPath* _lastAccessoryButtonTappedRowAtIndexPath;
	NSMutableArray* _scripts;
	NSMutableArray* _files;
	NSString* _path;
	UITableView* _tableView;
	NSMutableArray* _photos;

}

@property (nonatomic,retain) NSMutableArray * scripts;              //@synthesize scripts=_scripts - In the implementation block
@property (nonatomic,retain) NSString * path;                       //@synthesize path=_path - In the implementation block
@property (nonatomic,retain) UITableView * tableView;               //@synthesize tableView=_tableView - In the implementation block
@property (retain) NSMutableArray * files;                          //@synthesize files=_files - In the implementation block
@property (retain) NSMutableArray * photos;                         //@synthesize photos=_photos - In the implementation block
-(void)logView;
-(void)loadFiles;
-(id)getDontShowFeaturesNoteUserDefaultKey;
-(void)showNewFeaturesNote;
-(char)fileIsDirectory:(id)arg1 ;
-(id)pathForFile:(id)arg1 ;
-(id)fileAttributes:(id)arg1 ;
-(id)fileMIMEType:(id)arg1 ;
-(id)iconForFile:(id)arg1 ;
-(id)fileSize:(id)arg1 ;
-(id)fileCreateTime:(id)arg1 ;
-(char)isScriptAssignedActivatorTrigger:(id)arg1 ;
-(void)alertForFolderName:(id)arg1 ;
-(void)uploadToStore;
-(void)alertForScriptName:(id)arg1 ;
-(void)alertForEncryptPassword;
-(void)viewImage:(id)arg1 ;
-(void)renameFile:(id)arg1 toName:(id)arg2 ;
-(void)newDir:(id)arg1 ;
-(void)deleteAllScripts;
-(void)deleteAllFilesExceptScripts;
-(void)deleteAllFolders;
-(unsigned)numberOfPhotosInPhotoBrowser:(id)arg1 ;
-(id)photoBrowser:(id)arg1 photoAtIndex:(unsigned)arg2 ;
-(void)setScripts:(NSMutableArray *)arg1 ;
-(void)store;
-(NSMutableArray *)photos;
-(void)setPhotos:(NSMutableArray *)arg1 ;
-(void)dealloc;
-(id)init;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2 ;
-(id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(char)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)didReceiveMemoryWarning;
-(void)action;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(void)actionSheet:(id)arg1 willDismissWithButtonIndex:(int)arg2 ;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(NSString *)path;
-(void)setTableView:(UITableView *)arg1 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(char)arg1 ;
-(void)didRotateFromInterfaceOrientation:(int)arg1 ;
-(void)setPath:(NSString *)arg1 ;
-(UITableView *)tableView;
-(void)settings;
-(char)deleteFile:(id)arg1 ;
-(NSMutableArray *)scripts;
-(NSMutableArray *)files;
-(void)setFiles:(NSMutableArray *)arg1 ;
@end

