/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <AutoTouch/DYRateViewDelegate.h>

@class UIScrollView, NSDictionary;

@interface ScriptDetailsViewController : UIViewController <DYRateViewDelegate> {

	UIScrollView* scrollView;
	char isInitRating;
	char isRated;
	char _fromAuthorScriptList;
	NSDictionary* script;

}

@property (nonatomic,retain) NSDictionary * script; 
@property (assign,nonatomic) char fromAuthorScriptList;              //@synthesize fromAuthorScriptList=_fromAuthorScriptList - In the implementation block
-(void)clickDownload:(id)arg1 ;
-(void)setFromAuthorScriptList:(char)arg1 ;
-(char)fromAuthorScriptList;
-(void)clickOnAuthor;
-(void)emailToAuthor:(id)arg1 ;
-(void)rateView:(id)arg1 changedToNewRate:(id)arg2 ;
-(void)didReceiveMemoryWarning;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewDidLoad;
-(NSDictionary *)script;
-(void)setScript:(NSDictionary *)arg1 ;
@end

