/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface Script : NSObject {

	NSString* _title;
	NSString* _localPath;
	NSString* _createTime;
	NSString* _content;
	int _row;

}

@property (assign,nonatomic) int row;                                           //@synthesize row=_row - In the implementation block
@property (nonatomic,retain) NSString * title;                                  //@synthesize title=_title - In the implementation block
@property (nonatomic,retain) NSString * localPath;                              //@synthesize localPath=_localPath - In the implementation block
@property (nonatomic,retain) NSString * createTime;                             //@synthesize createTime=_createTime - In the implementation block
@property (getter=getContent,nonatomic,retain) NSString * content;              //@synthesize content=_content - In the implementation block
-(id)initWithTitle:(id)arg1 andLocalPath:(id)arg2 andCreateTime:(id)arg3 ;
-(void)setCreateTime:(NSString *)arg1 ;
-(id)initWithTitle:(id)arg1 andLocalPath:(id)arg2 andCreateTime:(id)arg3 andRow:(int)arg4 ;
-(char)deleteSelf;
-(NSString *)createTime;
-(int)row;
-(void)setTitle:(NSString *)arg1 ;
-(NSString *)title;
-(NSString *)localPath;
-(void)setLocalPath:(NSString *)arg1 ;
-(void)setRow:(int)arg1 ;
-(void)setContent:(NSString *)arg1 ;
-(id)getContent;
@end

