/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UITableViewController.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITextFieldDelegate.h>

@class UITextField, UIPlaceHolderTextView, NSMutableSet, UIBarButtonItem, NSDictionary;

@interface ScriptUpdateViewController : UITableViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate> {

	UITextField* titleTextField;
	UITextField* priceTextField;
	UIPlaceHolderTextView* descriptionTextView;
	NSMutableSet* selectedScreenSizes;
	UIBarButtonItem* rightButton;
	NSDictionary* script;

}

@property (nonatomic,retain) NSDictionary * script; 
-(void)viewTapped:(id)arg1 ;
-(void)save;
-(id)init;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2 ;
-(void)didReceiveMemoryWarning;
-(void)viewDidLoad;
-(NSDictionary *)script;
-(void)setScript:(NSDictionary *)arg1 ;
@end

