/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <AutoTouch/AutoTouch-Structs.h>
@class NSFileManager, NSCache, NSString, NSMutableArray;

@interface SDImageCache : NSObject {

	NSFileManager* _fileManager;
	int _maxCacheAge;
	unsigned _maxCacheSize;
	NSCache* _memCache;
	NSString* _diskCachePath;
	NSMutableArray* _customPaths;
	dispatch_queue_sRef _ioQueue;

}

@property (assign,nonatomic) unsigned maxMemoryCost; 
@property (assign,nonatomic) int maxCacheAge;                           //@synthesize maxCacheAge=_maxCacheAge - In the implementation block
@property (assign,nonatomic) unsigned maxCacheSize;                     //@synthesize maxCacheSize=_maxCacheSize - In the implementation block
@property (nonatomic,retain) NSCache * memCache;                        //@synthesize memCache=_memCache - In the implementation block
@property (nonatomic,retain) NSString * diskCachePath;                  //@synthesize diskCachePath=_diskCachePath - In the implementation block
@property (nonatomic,retain) NSMutableArray * customPaths;              //@synthesize customPaths=_customPaths - In the implementation block
@property (assign,nonatomic) dispatch_queue_sRef ioQueue;               //@synthesize ioQueue=_ioQueue - In the implementation block
+(id)sharedImageCache;
-(void)clearDisk;
-(void)clearMemory;
-(id)initWithNamespace:(id)arg1 ;
-(void)cleanDisk;
-(void)backgroundCleanDisk;
-(NSMutableArray *)customPaths;
-(void)setCustomPaths:(NSMutableArray *)arg1 ;
-(id)cachedFileNameForKey:(id)arg1 ;
-(NSString *)diskCachePath;
-(id)cachePathForKey:(id)arg1 inPath:(id)arg2 ;
-(NSCache *)memCache;
-(dispatch_queue_sRef)ioQueue;
-(id)defaultCachePathForKey:(id)arg1 ;
-(void)storeImage:(id)arg1 recalculateFromImage:(char)arg2 imageData:(id)arg3 forKey:(id)arg4 toDisk:(char)arg5 ;
-(id)imageFromMemoryCacheForKey:(id)arg1 ;
-(id)diskImageForKey:(id)arg1 ;
-(id)diskImageDataBySearchingAllPathsForKey:(id)arg1 ;
-(id)scaledImageForKey:(id)arg1 image:(id)arg2 ;
-(void)removeImageForKey:(id)arg1 fromDisk:(char)arg2 ;
-(void)clearDiskOnCompletion:(/*^block*/id)arg1 ;
-(int)maxCacheAge;
-(unsigned)maxCacheSize;
-(void)addReadOnlyCachePath:(id)arg1 ;
-(void)storeImage:(id)arg1 forKey:(id)arg2 ;
-(void)storeImage:(id)arg1 forKey:(id)arg2 toDisk:(char)arg3 ;
-(char)diskImageExistsWithKey:(id)arg1 ;
-(id)imageFromDiskCacheForKey:(id)arg1 ;
-(id)queryDiskCacheForKey:(id)arg1 done:(/*^block*/id)arg2 ;
-(void)setMaxMemoryCost:(unsigned)arg1 ;
-(unsigned)maxMemoryCost;
-(int)getDiskCount;
-(void)calculateSizeWithCompletionBlock:(/*^block*/id)arg1 ;
-(void)setMaxCacheAge:(int)arg1 ;
-(void)setMaxCacheSize:(unsigned)arg1 ;
-(void)setMemCache:(NSCache *)arg1 ;
-(void)setDiskCachePath:(NSString *)arg1 ;
-(void)setIoQueue:(dispatch_queue_sRef)arg1 ;
-(void)dealloc;
-(id)init;
-(unsigned)getSize;
-(void)removeImageForKey:(id)arg1 ;
@end

