/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <AutoTouch/AutoTouch-Structs.h>
@class NSOperationQueue, NSOperation, NSMutableDictionary;

@interface SDWebImageDownloader : NSObject {

	int _executionOrder;
	/*^block*/id _headersFilter;
	NSOperationQueue* _downloadQueue;
	NSOperation* _lastAddedOperation;
	NSMutableDictionary* _URLCallbacks;
	NSMutableDictionary* _HTTPHeaders;
	dispatch_queue_sRef _barrierQueue;
	double _downloadTimeout;

}

@property (assign,nonatomic) int maxConcurrentDownloads; 
@property (nonatomic,readonly) unsigned currentDownloadCount; 
@property (assign,nonatomic) double downloadTimeout;                               //@synthesize downloadTimeout=_downloadTimeout - In the implementation block
@property (assign,nonatomic) int executionOrder;                                   //@synthesize executionOrder=_executionOrder - In the implementation block
@property (nonatomic,copy) id headersFilter;                                       //@synthesize headersFilter=_headersFilter - In the implementation block
@property (nonatomic,retain) NSOperationQueue * downloadQueue;                     //@synthesize downloadQueue=_downloadQueue - In the implementation block
@property (assign,nonatomic,__weak) NSOperation * lastAddedOperation;              //@synthesize lastAddedOperation=_lastAddedOperation - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * URLCallbacks;                   //@synthesize URLCallbacks=_URLCallbacks - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * HTTPHeaders;                    //@synthesize HTTPHeaders=_HTTPHeaders - In the implementation block
@property (assign,nonatomic) dispatch_queue_sRef barrierQueue;                     //@synthesize barrierQueue=_barrierQueue - In the implementation block
+(id)sharedDownloader;
+(void)initialize;
-(NSOperationQueue *)downloadQueue;
-(double)downloadTimeout;
-(id)headersFilter;
-(id)callbacksForURL:(id)arg1 ;
-(void)removeCallbacksForURL:(id)arg1 ;
-(int)executionOrder;
-(NSOperation *)lastAddedOperation;
-(void)setLastAddedOperation:(NSOperation *)arg1 ;
-(void)addProgressCallback:(/*^block*/id)arg1 andCompletedBlock:(/*^block*/id)arg2 forURL:(id)arg3 createCallback:(/*^block*/id)arg4 ;
-(dispatch_queue_sRef)barrierQueue;
-(NSMutableDictionary *)URLCallbacks;
-(void)setMaxConcurrentDownloads:(int)arg1 ;
-(unsigned)currentDownloadCount;
-(int)maxConcurrentDownloads;
-(void)setDownloadTimeout:(double)arg1 ;
-(void)setExecutionOrder:(int)arg1 ;
-(void)setHeadersFilter:(id)arg1 ;
-(void)setDownloadQueue:(NSOperationQueue *)arg1 ;
-(void)setURLCallbacks:(NSMutableDictionary *)arg1 ;
-(void)setBarrierQueue:(dispatch_queue_sRef)arg1 ;
-(id)downloadImageWithURL:(id)arg1 options:(unsigned)arg2 progress:(/*^block*/id)arg3 completed:(/*^block*/id)arg4 ;
-(id)valueForHTTPHeaderField:(id)arg1 ;
-(void)setValue:(id)arg1 forHTTPHeaderField:(id)arg2 ;
-(void)dealloc;
-(id)init;
-(void)setHTTPHeaders:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)HTTPHeaders;
@end

