/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:30 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/SDWebImageOperation.h>

@class NSOperation;

@interface SDWebImageCombinedOperation : NSObject <SDWebImageOperation> {

	char _cancelled;
	/*^block*/id _cancelBlock;
	NSOperation* _cacheOperation;

}

@property (assign,getter=isCancelled,nonatomic) char cancelled;              //@synthesize cancelled=_cancelled - In the implementation block
@property (nonatomic,copy) id cancelBlock;                                   //@synthesize cancelBlock=_cancelBlock - In the implementation block
@property (nonatomic,retain) NSOperation * cacheOperation;                   //@synthesize cacheOperation=_cacheOperation - In the implementation block
-(void)setCancelBlock:(id)arg1 ;
-(void)setCacheOperation:(NSOperation *)arg1 ;
-(NSOperation *)cacheOperation;
-(id)cancelBlock;
-(void)setCancelled:(char)arg1 ;
-(char)isCancelled;
-(void)cancel;
@end

