/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:29 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Foundation/NSOperation.h>
#import <AutoTouch/SDWebImageOperation.h>

@class NSURLRequest, NSMutableData, NSURLConnection, NSThread;

@interface SDWebImageDownloaderOperation : NSOperation <SDWebImageOperation> {

	unsigned long width;
	unsigned long height;
	int orientation;
	char responseFromCached;
	char _executing;
	char _finished;
	NSURLRequest* _request;
	unsigned _options;
	/*^block*/id _progressBlock;
	/*^block*/id _completedBlock;
	/*^block*/id _cancelBlock;
	int _expectedSize;
	NSMutableData* _imageData;
	NSURLConnection* _connection;
	NSThread* _thread;
	unsigned _backgroundTaskId;

}

@property (nonatomic,readonly) NSURLRequest * request;                       //@synthesize request=_request - In the implementation block
@property (nonatomic,readonly) unsigned options;                             //@synthesize options=_options - In the implementation block
@property (nonatomic,copy) id progressBlock;                                 //@synthesize progressBlock=_progressBlock - In the implementation block
@property (nonatomic,copy) id completedBlock;                                //@synthesize completedBlock=_completedBlock - In the implementation block
@property (nonatomic,copy) id cancelBlock;                                   //@synthesize cancelBlock=_cancelBlock - In the implementation block
@property (assign,getter=isExecuting,nonatomic) char executing;              //@synthesize executing=_executing - In the implementation block
@property (assign,getter=isFinished,nonatomic) char finished;                //@synthesize finished=_finished - In the implementation block
@property (assign,nonatomic) int expectedSize;                               //@synthesize expectedSize=_expectedSize - In the implementation block
@property (nonatomic,retain) NSMutableData * imageData;                      //@synthesize imageData=_imageData - In the implementation block
@property (nonatomic,retain) NSURLConnection * connection;                   //@synthesize connection=_connection - In the implementation block
@property (retain) NSThread * thread;                                        //@synthesize thread=_thread - In the implementation block
@property (assign,nonatomic) unsigned backgroundTaskId;                      //@synthesize backgroundTaskId=_backgroundTaskId - In the implementation block
+(int)orientationFromPropertyValue:(int)arg1 ;
-(id)scaledImageForKey:(id)arg1 image:(id)arg2 ;
-(id)initWithRequest:(id)arg1 options:(unsigned)arg2 progress:(/*^block*/id)arg3 completed:(/*^block*/id)arg4 cancelled:(/*^block*/id)arg5 ;
-(char)shouldContinueWhenAppEntersBackground;
-(unsigned)backgroundTaskId;
-(void)setBackgroundTaskId:(unsigned)arg1 ;
-(id)completedBlock;
-(void)cancelInternalAndStop;
-(void)cancelInternal;
-(void)setCompletedBlock:(id)arg1 ;
-(void)setExpectedSize:(int)arg1 ;
-(void)setCancelBlock:(id)arg1 ;
-(id)cancelBlock;
-(id)connection:(id)arg1 willCacheResponse:(id)arg2 ;
-(char)isConcurrent;
-(void)cancel;
-(void)done;
-(void)start;
-(NSURLRequest *)request;
-(void)reset;
-(void)connection:(id)arg1 didFailWithError:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveData:(id)arg2 ;
-(void)connectionDidFinishLoading:(id)arg1 ;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2 ;
-(unsigned)options;
-(NSURLConnection *)connection;
-(char)isFinished;
-(char)isExecuting;
-(void)setConnection:(NSURLConnection *)arg1 ;
-(void)setExecuting:(char)arg1 ;
-(NSThread *)thread;
-(void)setThread:(NSThread *)arg1 ;
-(void)setFinished:(char)arg1 ;
-(int)expectedSize;
-(NSMutableData *)imageData;
-(void)setImageData:(NSMutableData *)arg1 ;
-(id)progressBlock;
-(void)setProgressBlock:(id)arg1 ;
-(char)connection:(id)arg1 canAuthenticateAgainstProtectionSpace:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2 ;
@end

