/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:30 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SDWebImagePrefetcherDelegate;
@class SDWebImageManager, NSArray;

@interface SDWebImagePrefetcher : NSObject {

	unsigned _options;
	id<SDWebImagePrefetcherDelegate> _delegate;
	SDWebImageManager* _manager;
	NSArray* _prefetchURLs;
	unsigned _requestedCount;
	unsigned _skippedCount;
	unsigned _finishedCount;
	/*^block*/id _completionBlock;
	/*^block*/id _progressBlock;
	double _startedTime;

}

@property (assign,nonatomic) unsigned maxConcurrentDownloads; 
@property (assign,nonatomic) unsigned options;                                              //@synthesize options=_options - In the implementation block
@property (assign,nonatomic,__weak) id<SDWebImagePrefetcherDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) SDWebImageManager * manager;                                   //@synthesize manager=_manager - In the implementation block
@property (nonatomic,retain) NSArray * prefetchURLs;                                        //@synthesize prefetchURLs=_prefetchURLs - In the implementation block
@property (assign,nonatomic) unsigned requestedCount;                                       //@synthesize requestedCount=_requestedCount - In the implementation block
@property (assign,nonatomic) unsigned skippedCount;                                         //@synthesize skippedCount=_skippedCount - In the implementation block
@property (assign,nonatomic) unsigned finishedCount;                                        //@synthesize finishedCount=_finishedCount - In the implementation block
@property (assign,nonatomic) double startedTime;                                            //@synthesize startedTime=_startedTime - In the implementation block
@property (nonatomic,copy) id completionBlock;                                              //@synthesize completionBlock=_completionBlock - In the implementation block
@property (nonatomic,copy) id progressBlock;                                                //@synthesize progressBlock=_progressBlock - In the implementation block
+(id)sharedImagePrefetcher;
-(void)setMaxConcurrentDownloads:(unsigned)arg1 ;
-(unsigned)maxConcurrentDownloads;
-(NSArray *)prefetchURLs;
-(unsigned)requestedCount;
-(void)setRequestedCount:(unsigned)arg1 ;
-(unsigned)finishedCount;
-(void)setFinishedCount:(unsigned)arg1 ;
-(unsigned)skippedCount;
-(void)setSkippedCount:(unsigned)arg1 ;
-(void)startPrefetchingAtIndex:(unsigned)arg1 ;
-(void)reportStatus;
-(void)prefetchURLs:(id)arg1 progress:(/*^block*/id)arg2 completed:(/*^block*/id)arg3 ;
-(void)cancelPrefetching;
-(void)setStartedTime:(double)arg1 ;
-(void)setPrefetchURLs:(NSArray *)arg1 ;
-(void)prefetchURLs:(id)arg1 ;
-(double)startedTime;
-(void)setDelegate:(id<SDWebImagePrefetcherDelegate>)arg1 ;
-(id)init;
-(id<SDWebImagePrefetcherDelegate>)delegate;
-(void)setCompletionBlock:(id)arg1 ;
-(id)completionBlock;
-(void)setOptions:(unsigned)arg1 ;
-(unsigned)options;
-(SDWebImageManager *)manager;
-(void)setManager:(SDWebImageManager *)arg1 ;
-(id)progressBlock;
-(void)setProgressBlock:(id)arg1 ;
@end

