/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:30 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol SDWebImageManagerDelegate;
@class SDImageCache, SDWebImageDownloader, NSMutableArray;

@interface SDWebImageManager : NSObject {

	id<SDWebImageManagerDelegate> _delegate;
	SDImageCache* _imageCache;
	SDWebImageDownloader* _imageDownloader;
	/*^block*/id _cacheKeyFilter;
	NSMutableArray* _failedURLs;
	NSMutableArray* _runningOperations;

}

@property (assign,nonatomic,__weak) id<SDWebImageManagerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) SDImageCache * imageCache;                                  //@synthesize imageCache=_imageCache - In the implementation block
@property (nonatomic,retain) SDWebImageDownloader * imageDownloader;                     //@synthesize imageDownloader=_imageDownloader - In the implementation block
@property (copy) id cacheKeyFilter;                                                      //@synthesize cacheKeyFilter=_cacheKeyFilter - In the implementation block
@property (nonatomic,retain) NSMutableArray * failedURLs;                                //@synthesize failedURLs=_failedURLs - In the implementation block
@property (nonatomic,retain) NSMutableArray * runningOperations;                         //@synthesize runningOperations=_runningOperations - In the implementation block
+(id)sharedManager;
-(id)downloadWithURL:(id)arg1 options:(unsigned)arg2 progress:(/*^block*/id)arg3 completed:(/*^block*/id)arg4 ;
-(id)createCache;
-(id)cacheKeyFilter;
-(id)cacheKeyForURL:(id)arg1 ;
-(NSMutableArray *)failedURLs;
-(NSMutableArray *)runningOperations;
-(SDWebImageDownloader *)imageDownloader;
-(char)diskImageExistsForURL:(id)arg1 ;
-(void)cancelAll;
-(void)setImageDownloader:(SDWebImageDownloader *)arg1 ;
-(void)setCacheKeyFilter:(id)arg1 ;
-(void)setFailedURLs:(NSMutableArray *)arg1 ;
-(void)setRunningOperations:(NSMutableArray *)arg1 ;
-(SDImageCache *)imageCache;
-(void)setDelegate:(id<SDWebImageManagerDelegate>)arg1 ;
-(id)init;
-(id<SDWebImageManagerDelegate>)delegate;
-(char)isRunning;
-(void)setImageCache:(SDImageCache *)arg1 ;
@end

