/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <UIKit/UITableViewController.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UIActionSheetDelegate.h>
#import <UIKit/UISearchBarDelegate.h>

@class NSString, NSMutableArray, UISearchBar, UIButton;

@interface StoreViewController : UITableViewController <UITableViewDelegate, UITableViewDataSource, UIActionSheetDelegate, UISearchBarDelegate> {

	NSString* currentSearchText;
	int currentPageIndex;
	int pageSize;
	char isBottom;
	char isLoadingMore;
	char alreadyTipped;
	NSMutableArray* scripts;
	int _scriptListQueryType;
	NSString* _authorEmail;
	UISearchBar* searchBar;
	UIButton* btnAccessoryView;

}

@property (assign,nonatomic) int scriptListQueryType;                  //@synthesize scriptListQueryType=_scriptListQueryType - In the implementation block
@property (nonatomic,retain) NSString * authorEmail;                   //@synthesize authorEmail=_authorEmail - In the implementation block
@property (nonatomic,retain) UIButton * btnAccessoryView; 
@property (nonatomic,retain) UISearchBar * searchBar; 
@property (nonatomic,retain) NSMutableArray * scripts; 
-(void)setScriptListQueryType:(int)arg1 ;
-(void)setScripts:(NSMutableArray *)arg1 ;
-(int)scriptListQueryType;
-(void)mine;
-(void)reloadTableViewDataSource;
-(void)ClickControlAction:(id)arg1 ;
-(void)loadData:(char)arg1 ;
-(void)clickDownload:(id)arg1 ;
-(void)deleteScript;
-(void)controlAccessoryView:(float)arg1 ;
-(UIButton *)btnAccessoryView;
-(NSString *)authorEmail;
-(void)setAuthorEmail:(NSString *)arg1 ;
-(void)setBtnAccessoryView:(UIButton *)arg1 ;
-(id)init;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3 ;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(void)didReceiveMemoryWarning;
-(void)action;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(void)viewDidLoad;
-(UISearchBar *)searchBar;
-(void)searchBar:(id)arg1 textDidChange:(id)arg2 ;
-(char)searchBarShouldBeginEditing:(id)arg1 ;
-(void)searchBarCancelButtonClicked:(id)arg1 ;
-(void)searchBarSearchButtonClicked:(id)arg1 ;
-(void)setSearchBar:(UISearchBar *)arg1 ;
-(void)logout;
-(NSMutableArray *)scripts;
@end

