/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:30 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UINavigationController.h>

@class UIColor, SVWebViewController;

@interface SVModalWebViewController : UINavigationController {

	UIColor* _barsTintColor;
	SVWebViewController* _webViewController;

}

@property (nonatomic,retain) UIColor * barsTintColor;                              //@synthesize barsTintColor=_barsTintColor - In the implementation block
@property (nonatomic,retain) SVWebViewController * webViewController;              //@synthesize webViewController=_webViewController - In the implementation block
-(UIColor *)barsTintColor;
-(void)setBarsTintColor:(UIColor *)arg1 ;
-(id)initWithAddress:(id)arg1 ;
-(void)viewWillAppear:(char)arg1 ;
-(id)initWithURL:(id)arg1 ;
-(SVWebViewController *)webViewController;
-(void)setWebViewController:(SVWebViewController *)arg1 ;
@end

