/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol UIAlertViewDelegate <NSObject>
@optional
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
-(void)alertViewCancel:(id)arg1;
-(char)alertViewShouldEnableFirstOtherButton:(id)arg1;
-(void)didPresentAlertView:(id)arg1;
-(void)willPresentAlertView:(id)arg1;
-(void)alertView:(id)arg1 willDismissWithButtonIndex:(int)arg2;

@end

