/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/AutoTouch-Structs.h>
#import <UIKit/UITextView.h>

@class NSString, UIColor, UILabel;

@interface UIPlaceHolderTextView : UITextView {

	NSString* _placeholder;
	UIColor* _placeholderColor;
	UILabel* _placeHolderLabel;

}

@property (nonatomic,retain) NSString * placeholder;                  //@synthesize placeholder=_placeholder - In the implementation block
@property (nonatomic,retain) UIColor * placeholderColor;              //@synthesize placeholderColor=_placeholderColor - In the implementation block
@property (nonatomic,retain) UILabel * placeHolderLabel;              //@synthesize placeHolderLabel=_placeHolderLabel - In the implementation block
-(UIColor *)placeholderColor;
-(void)setPlaceholderColor:(UIColor *)arg1 ;
-(UILabel *)placeHolderLabel;
-(void)setPlaceHolderLabel:(UILabel *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)drawRect:(CGRect)arg1 ;
-(void)setText:(id)arg1 ;
-(void)awakeFromNib;
-(void)setPlaceholder:(NSString *)arg1 ;
-(void)textChanged:(id)arg1 ;
-(NSString *)placeholder;
@end

