/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/UMANBaseEvent.h>

@class NSString, NSDictionary;

@interface UMANEvent : UMANBaseEvent {

	NSString* _event_id;
	NSString* _label;
	int _acc;
	int _du;
	NSDictionary* _values;

}

@property (nonatomic,copy) NSString * event_id;                  //@synthesize event_id=_event_id - In the implementation block
@property (nonatomic,copy) NSString * label;                     //@synthesize label=_label - In the implementation block
@property (assign,nonatomic) int acc;                            //@synthesize acc=_acc - In the implementation block
@property (assign,nonatomic) int du;                             //@synthesize du=_du - In the implementation block
@property (nonatomic,retain) NSDictionary * values;              //@synthesize values=_values - In the implementation block
-(void)setEvent_id:(NSString *)arg1 ;
-(void)setAcc:(int)arg1 ;
-(void)setDu:(int)arg1 ;
-(void)updateDu;
-(int)du;
-(NSString *)event_id;
-(int)acc;
-(void)dealloc;
-(id)init;
-(void)setValues:(NSDictionary *)arg1 ;
-(NSDictionary *)values;
-(NSString *)label;
-(void)setLabel:(NSString *)arg1 ;
-(id)attributes;
@end

