/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/UMANBaseEvent.h>

@class NSMutableArray;

@interface UMANTerminate : UMANBaseEvent {

	double _duration;
	NSMutableArray* _pageViews;
	double _latitude;
	double _longitude;
	long long _gps_time;

}

@property (assign,nonatomic) double duration;                         //@synthesize duration=_duration - In the implementation block
@property (nonatomic,retain) NSMutableArray * pageViews;              //@synthesize pageViews=_pageViews - In the implementation block
@property (assign,nonatomic) double latitude;                         //@synthesize latitude=_latitude - In the implementation block
@property (assign,nonatomic) double longitude;                        //@synthesize longitude=_longitude - In the implementation block
@property (assign,nonatomic) long long gps_time;                      //@synthesize gps_time=_gps_time - In the implementation block
-(NSMutableArray *)pageViews;
-(void)setGps_time:(long long)arg1 ;
-(void)setPageViews:(NSMutableArray *)arg1 ;
-(long long)gps_time;
-(void)setLatitude:(double)arg1 ;
-(void)setLongitude:(double)arg1 ;
-(void)dealloc;
-(id)init;
-(double)duration;
-(void)setDuration:(double)arg1 ;
-(id)attributes;
-(double)latitude;
-(double)longitude;
-(id)initWithDuration:(double)arg1 ;
@end

