/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface UMANUtil : NSObject
+(id)sdkTypeString;
+(id)sdkVersionString;
+(id)appDisplayNameString;
+(id)urlEncode:(id)arg1 ;
+(id)appVersionString;
+(id)deviceModelString;
+(id)osVersionString;
+(id)md5Value:(id)arg1 ;
+(id)deflatedData:(id)arg1 ;
+(id)accessString;
+(char)isDeviceJailBreak;
+(char)isAppPirate;
+(id)appPackageNameString;
+(id)timeString;
+(id)JSONFragment:(id)arg1 ;
+(id)JSONValue:(id)arg1 ;
+(char)deviceIsDebugging;
+(id)returnCheck:(id)arg1 ;
+(id)umStringDecode:(id)arg1 ;
+(id)mData;
+(id)deflatedDataPrefixedWith:(id)arg1 level:(int)arg2 source:(id)arg3 ;
+(id)deviceMacAddressString;
+(id)countryString;
+(id)protocolVersionString;
+(id)appShortVersionString;
+(id)osString;
+(id)timezoneString;
+(id)resolutionString;
+(id)carrierString;
+(id)deviceJailBreakString;
+(id)openUDIDString;
+(id)appPirateString;
+(id)itemIdString;
+(id)pDateString;
+(id)getString:(id)arg1 bytesLength:(int)arg2 ;
+(id)umStringEncode:(id)arg1 ;
+(id)deviceIDAdverString;
+(id)deviceIDVendorString;
+(id)orientationString;
+(id)sessionId;
+(id)languageString;
+(id)dateString;
+(char)isPad;
-(id)JSONRepresentation:(id)arg1 ;
@end

