/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSMutableDictionary;

@interface UMANEkv : NSObject {

	double ts;
	int du;
	NSString* _id;
	NSString* _key;
	NSMutableDictionary* _values;

}

@property (assign,nonatomic) double ts; 
@property (assign,nonatomic) int du; 
@property (nonatomic,copy) NSString * id;                               //@synthesize id=_id - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * values;              //@synthesize values=_values - In the implementation block
@property (nonatomic,copy) NSString * key;                              //@synthesize key=_key - In the implementation block
-(void)setDu:(int)arg1 ;
-(void)updateDu;
-(int)du;
-(id)initWithId:(id)arg1 key:(id)arg2 values:(id)arg3 ;
-(double)ts;
-(void)setTs:(double)arg1 ;
-(void)dealloc;
-(id)description;
-(void)setValues:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)values;
-(NSString *)key;
-(void)setKey:(NSString *)arg1 ;
-(id)attributes;
-(NSString *)id;
-(void)setId:(NSString *)arg1 ;
@end

