/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Foundation/NSOperation.h>

@class NSString;

@interface UMANWorker : NSOperation {

	NSString* _json;

}

@property (nonatomic,copy) NSString * json;              //@synthesize json=_json - In the implementation block
-(NSString *)json;
-(void)postData;
-(char)postDataToServer:(id)arg1 ;
-(void)setJson:(NSString *)arg1 ;
-(void)dealloc;
-(void)main;
@end

