/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:24 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <AutoTouch/UMANBaseEvent.h>

@class NSString;

@interface UMANError : UMANBaseEvent {

	NSString* _context;

}

@property (nonatomic,copy) NSString * context;              //@synthesize context=_context - In the implementation block
-(void)dealloc;
-(id)init;
-(NSString *)context;
-(void)setContext:(NSString *)arg1 ;
-(id)attributes;
@end

