/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 28, 2014 at 4:16:25 PM Central European Standard Time
* Operating System: Version 7.1.2 (Build 11D257)
* Image Source: /private/var/mobile/Downloads/AutoTouch
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import <AutoTouch/AutoTouch-Structs.h>
@interface Utils : NSObject
+(id)appInstalledList;
+(id)getSerialNumber;
+(id)getScreenSize;
+(id)imageWithImage:(id)arg1 scaledToWidth:(float)arg2 ;
+(id)imageWithImage2:(id)arg1 scaledToWidth:(float)arg2 ;
+(CGRect)currentScreenBoundsDependOnOrientation;
+(id)sha1:(id)arg1 ;
@end

